### ISSUE TITLE
dynamically changing tabs

### ISSUE THREAD

**Issue by siddu-ms** [zyra/ionic-super-tabs#108]
i have two tabs "Items" and "Create Item", items has list of items when i tap on any items it should able change "Create item" to "Edit items", upto this part is working for me. now i am in "Edit item tab" and i do not want to edit item, in this case if i swipe back to "Items" Page , the "Edit items" should change to "Create item". 
my html is : 
```html
<super-tabs class = "artist-tabs fade-in-not-out" [selectedTabIndex]="artistTabIndex" (tabSelect)="onTabSelect($event)">
    <super-tab [root]="tab1Root" title="ITEMS"></super-tab>
    <super-tab [root]="tab2Root" title="{{edit/create}}"></super-tab>
  </super-tabs> 
```

AND ts file is :
```ts
this.tab2Root =  this.iscreateTab? CreateItem : EditItem ;
```
And everything works fine. when i swipe from "Edit Item" screen it appears 3tabs, how can i overcome from this problem . any solutions?

**Comment by ihadeed** [comment]
Just to make sure I understand everything correctly, you are trying to have the second tab dynamically change based on some condition. You would like to change the tab's title, as well as the page that it takes the user to. 

If that's what you're trying to do, you can change the root of the nav by calling `setRoot` method on it. Example:
```html
<super-tabs ...>
   ...
   <super-tab #myTab [root]="tab2Root" title="..."></super-tab>
</super-tabs>
```
```ts
// fetch it with ViewChild decorator
@ViewChild('myTab') dynamicTab: SuperTab;

// later in code
this.dynamicTab.setRoot(CreateItem);
```

As for changing the title, I think I will need to edit the module to make that work. At the moment it only accepts inputs on initialization, and does not update the component if you edit those inputs later on.
