### ISSUE TITLE
super-tabs doesn't work if I translate all titles with ngx-translate

### ISSUE THREAD

**Issue by vdias38** [zyra/ionic-super-tabs#151]
I've tried to translate titles of tabs using ngx-translate (@ngx-translate/core@7.2.0), it doesn't work if I translate all, like below:

```javascript
  <super-tabs [config]="{ sideMenu: 'left' }">
    <super-tab [root]="live" [title]="'Live' | translate"></super-tab>
    <super-tab [root]="latest" [title]="'Latest News' | translate"></super-tab>
    <super-tab [root]="contacts" [title]="'Contacts' | translate"></super-tab>
  </super-tabs>
```

BUT works fine if I leave one title non-translated , like below:

```javascript
  <super-tabs [config]="{ sideMenu: 'left' }">
    <super-tab [root]="live" title="Ao vivo"></super-tab>
    <super-tab [root]="latest" [title]="'Latest News' | translate"></super-tab>
    <super-tab [root]="contacts" [title]="'Contacts' | translate"></super-tab>
  </super-tabs>
```

**Comment by BenHen75** [comment]
Hi, try this:
`<super-tab [root]="live" [title]="( 'Live' | translate)"></super-tab>`

**Comment by elbidone** [comment]
I've tried the suggestion but didn't work, also tries `<super-tab [root]="live" title="{{'Live' | translate}}"></super-tab>`, without success.

**Comment by julianCast** [comment]
I'm using ngx-translate and is working:
	`<super-tab [root]="tab1Root" title="{{ 'MENU.GALLERY' | translate }}"></super-tab>`

**Comment by elbidone** [comment]
Hi @julianCast, it also works for me, but not if all titles of super-tab elements are translated.
Could you share with us your whole super-tabs element (include all super-tab elements) ?

**Comment by julianCast** [comment]
Sure!
```
<super-tabs #myTabs selectedTabIndex="{{iTab}}" toolbarColor="white" toolbarBackground="dark" (tabSelect)="checkTab($event)">
   <super-tab [root]="tab1Root" title="{{ 'MENU.GALLERY' | translate }}"></super-tab>
   <super-tab [root]="tab2Root" title="{{ 'MENU.MUSIC' | translate }}"></super-tab> 
   <super-tab [root]="tab3Root" title="{{ 'MENU.LIBRARY' | translate }}"></super-tab>
</super-tabs>
```

**Comment by elbidone** [comment]
Well... very strange same code doesn't work for me

```
  <super-tabs [config]="{ sideMenu: 'left' }">
    <super-tab [root]="live" title="{{'Live' | translate}}"></super-tab>
    <super-tab [root]="latest" title="{{'Latest News' | translate}}"></super-tab>
    <super-tab [root]="contacts" title="{{'Contacts' | translate}}"></super-tab>
  </super-tabs>
```

Below versions I use:

```
$ npm ls @angular/common ionic-angular ionic2-super-tabs --depth 0
├── @angular/common@4.1.3 
├── ionic-angular@3.6.0 
└── ionic2-super-tabs@4.0.1 
```

**Comment by BenHen75** [comment]
`<super-tab [root]="latest" title="{{'Latest News' | translate}}"></super-tab>`
should be
`<super-tab [root]="latest" title="{{'LATEST_NEWS' | translate}}"></super-tab>`

and you ang.json:
`  "LATEST_NEWS": "Latest News",`

**Comment by ihadeed** [comment]
Since ngx-translate is async and it takes time to fetch the translation, it doesn't actually update the super tabs component. This is a flaw with super-tabs, related to some other issue(s). I plan to fix it in the next release.

For now, if you can somehow make sure that the translation is ready before the super-tabs component is rendered, it should work fine.

**Comment by kunalgrover05** [comment]
Funnily, there is an open issue on Ionic tabs as well, and using the same workaround fixes the problem.
https://github.com/ionic-team/ionic/issues/8439

Workaround: Change this
```
<super-tab [root]="latest" title="{{'Latest News' | translate}}"></super-tab>
```
to add a space after `}}`
```
<super-tab [root]="latest" title="{{'Latest News' | translate}} "></super-tab>
```
