### ISSUE TITLE
indicator & scrollTabs is not working after loading some tabs from sqlite database

### ISSUE THREAD

**Issue by shahkhalid-me** [zyra/ionic-super-tabs#173]
When i add static tabs `scrollTabs `property is working perfectly. But when the tabs are dynamic then tabs indicator & scrollTabs property is not working

```
<super-tabs id="mainTabs" [config]="{ sideMenu: 'left' }" scrollTabs="true" toolbarColor="light" toolbarBackground="danger" indicatorColor="yellow" badgeColor="light" (tabSelect)="onTabSelect($event)">
        <super-tab [rootParams]="params" [swipeBackEnabled]="false" [root]="page" title="Latest" id="latest"></super-tab>
        <super-tab *ngFor="let topic of myTopics" [rootParams]="params" [root]="page" [title]="topic.title" [id]="topic.slug"></super-tab>
 </super-tabs>
```

**Comment by ihadeed** [comment]
The component only loads the tabs when its initialized. You have to add an *ngIf on your `super-tabs` component to ensure that it starts rendering after your data has been fetched. 

This behaviour will be changed in the near future to make it possible to use only *ngFor without an *ngIf
