### ISSUE TITLE
Will the plugin be updated for current ionic versions?

### ISSUE THREAD

**Issue by JaneDawson** [zyra/ionic-super-tabs#192]
Hi @ihadeed,

as you probably know, there are some major issues with the super-tabs plugin and the current release of Ionic CLI 3.13.x, especially with `run *platform* --prod`.

For me, this plugin is one of the most important plugins, since it dominates the navigation process of the user and hence is visible almost all the time. However, with the current issues, it's not reliable anymore, as it used to be. There are issues with the css-file not beeing copied when building with `--prod`. And sometimes the tabs even fully disappear. Only solution for the user: Close and restart the app. No good UX...

Hence my question: Are you planning on updating this great plugin? Otherwise we had to roll back to an older version of Ionic which doesn't seem to be a great idea either...

Thanks for your answer. As said in other issue-topics, I really appreciate the work you are doing here. Thank you!

**Comment by ihadeed** [comment]
Hey @JaneDawson 

Yes the plugin will be updated soon. thank you for your patience.  

I think the `--prod` issues are from the `ionic-app-scripts` package and they should be fixed in the latest release (or nightly).
