### ISSUE TITLE
iOS 11: Position: fixed div doesn't show (is moved to wrong tab-page)

### ISSUE THREAD

**Issue by JaneDawson** [zyra/ionic-super-tabs#222]
I have a 4-tabs-layout. On tab 2 there is a div which is positioned with `position: fixed`. This leads to strange behavior on iOS 11. When starting the app, the div is not shown at all. When using the debugging tools, I can see, that the div is in background of tab1 - that is strange! You cannot see it, but only recognize it with the debugging tools.

When I start sliding through the tabs, the div at some point shows on its correct position in the correct tab.

Since using some plugins which rely on Angular4, I cannot upgrade to ionic-angular 3.9.2 (using Angular5) and hence to the most current version of the ionic2-super-tabs plugin (4.1.5).

Does anybody have any idea, what this could be about? Thanks for you help!

**Ionic2-super-tabs version:**
4.1.4

**Ionic info**
```
cli packages: 

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.2.3 ios 4.5.0-dev
    Ionic Framework    : ionic-angular 3.8.0

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.2 
    Node       : v8.9.1
    npm        : 2.15.12 
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55 
```

**Comment by JaneDawson** [comment]
Additional remark: If I change the div to `position: absolute` it is shown as expected. However, I need it to be `fixed`, to prevent it from being scrolled.

**Comment by ihadeed** [comment]
Won't fix this unless it becomes a very common issue. Feel free to fork the repo & do the necessary changes needed to fit your specific needs.

**Comment by eduardoRoth** [comment]
@JaneDawson , not sure which part of the div inside the tab you want to be fixed and not scrolled, but if you place your div inside `ion-header` or `ion-footer` of the tab's html, it'll be fixed and not scrolled through the page. Hope this helps.

**Comment by stegithub** [comment]
I've the same issue, also adding ion-header or ion-footer.
