### ISSUE TITLE
Error: Uncaught (in promise): invalid link: revenue

### ISSUE THREAD

**Issue by matthildenbrand** [zyra/ionic-super-tabs#253]
I am attempting to loop through an array and pass the name values to display the tabs. I am using super tabs version 4.2.0.

```
<super-tabs scrollTabs tappable (tabSelect)="onTabSelect($event)" [ngClass]="{active: (menuActive.menuActive)}" (click)="tabClick()">
    <div *ngFor="let item of availableModules">
      <super-tab [root]="item.name.toLowerCase()" [attr.title]="item.name" [attr.id]="item.name.toLowerCase()"></super-tab>
    </div>
</super-tabs>
```

When attempt to run the code above I get the following error:
`
Error: Uncaught (in promise): invalid link: revenue
`

However if I hardcode the values in, super tabs render the number of tabs equal to items in array. Can we not pass the values in dynamically while looping through the array for some reason?

Hardcoded values, in this case it renders 2 revenue tabs (one for each item in array)
```
<super-tabs scrollTabs tappable (tabSelect)="onTabSelect($event)" [ngClass]="{active: (menuActive.menuActive)}" (click)="tabClick()">
    <div *ngFor="let item of availableModules">
      <super-tab [root]="revenue" title="Revenue" id="revenue"></super-tab>
    </div>
</super-tabs>
```

```
Ionic Framework: ^3.6.0
Ionic App Scripts: 1.3.7
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 8.9.2
OS Platform: macOS High Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75 Mobile/14E5239e Safari/602.1
```

Thoughts?

**Comment by ihadeed** [comment]
Is your array ready before the page loads? or is there an async function that prepares that Array?

**Comment by matthildenbrand** [comment]
I am using rxjs observable on the page constructor to get the array from the store then save it as a local variable:

```
constructor(
    public navCtrl: NavController,
    public navParams: NavParams,
    private superTabsCtrl: SuperTabsController,
    public storage: Storage,
    public alertCtrl: AlertController,
    private store: Store<AppState>) {

    this.menuStatus = store.select<MenuStatus>('menuStatus' as any);
    this.menuStatus.subscribe(status => {
      this.menuActive = status
    });

    this.availableModulesStatus = store.select<Modules>('availableModules' as any);
    this.availableModulesStatus.subscribe(res => {
      this.availableModules = res
    });
  }
```

I know it's passing the value from my array to [root] because when I remove the .toLowerCase() method the error changes to the exact value in my array.

```
Error: Uncaught (in promise): invalid link: Revenue
```

Is it that Super Tabs is initializing with empty value being passed to [root], but then tries to render with my array values being assigned to [root] (in this case, revenue) and causing an exception?

**Comment by ihadeed** [comment]
Yeah then you need to have a local variable `isArrayReady: boolean = false`, set the value of it to `true` once you have loaded the necessary data. Then add `*ngIf="isArrayReady"` to your `super-tabs` element.

**Comment by matthildenbrand** [comment]
I tried your suggestion and got the same outcome. 

It seems like Super Tabs is initializing with the single super tab element before angular finishes looping through the array and adding additional super tabs. So, there is a disconnect between the super tab elements when initialized and the super tab elements when rendered, if that makes any sense?

Getting this to work isn't super urgent for me. I will see if I can find time to go through source and find the issue and possibly fix it.

Thanks for the responses and I love super tabs it's been great for me so far!
