### ISSUE TITLE
--prod build issues

### ISSUE THREAD

**Issue by ihadeed** [zyra/ionic-super-tabs#254]
Not enough data collected... so far things seem random
- content isn't displayed (the page inside `super-tab`)
- tab indicator not showing
- tab buttons don't do anything
- tab buttons container doesn't move

These issues don't always occur, but they most likely will. 

For now refrain from building with `--prod` flag if you use this module. Will fix these issues when I get a chance.

**Comment by webgrafia** [comment]
I confirm problems...

**Comment by Udith-Murali-K** [comment]
Is this fixed??

**Comment by ihadeed** [comment]
@Udith-Murali-K The issue is still open, so no.

**Comment by Saqib92** [comment]
still facing this issue with `--prod` build.
