### ISSUE TITLE
Unable to have horizontal scroll on any page

### ISSUE THREAD

**Issue by Srijan1702** [zyra/ionic-super-tabs#256]
I am not able to use horizontal scroll in any page as super tab overrides the scroll. Instead of scrolling it changes the page. How can I achieve this, please help!!!

**Comment by eduardoRoth** [comment]
Hi @Srijan1702 ,

Can you tell me which version are you using?

**Comment by Srijan1702** [comment]
Hello @eduardoRoth 
I am using Ionic3.

**Comment by eduardoRoth** [comment]
I mean, which version of `ionic2-super-tabs` are you using? Latest version has an attribute to allow scrolling elements inside the tab.

**allowElementScroll**
*Allow elements inside tabs to be dragged before triggering the tab swipe event.*

**Comment by Srijan1702** [comment]
I am using v4.2.2

**Comment by eduardoRoth** [comment]
Have your tried using `allowElementScroll` param?

**Comment by Srijan1702** [comment]
I have tried that.

<super-tabs allowElementScroll="true">
  <super-tab [root]="tab1Root"  icon="md-calendar"></super-tab>
  <super-tab [root]="tab5Root"  icon="ios-settings-outline"></super-tab>
</super-tabs>

**Comment by eduardoRoth** [comment]
`allowElementScroll` is a param from `config` attribute, try it like this:

```
<super-tabs config="{allowElementScroll: false}">
  <super-tab [root]="tab1Root"  icon="md-calendar"></super-tab>
  <super-tab [root]="tab5Root"  icon="ios-settings-outline"></super-tab>
</super-tabs>
```

**Comment by Srijan1702** [comment]
I just tried but it's still not working. Please let me know what's I am doing wrong.

```
<super-tabs config="{allowElementScroll: true}">
  <super-tab [root]="tab1Root"  icon="md-calendar"></super-tab>
  <super-tab [root]="tab5Root"  icon="ios-settings-outline"></super-tab>
</super-tabs>
```

**Comment by eduardoRoth** [comment]
Let me create a test project and check what's happening.

Also, allowElementScroll works by increasing `dragThreshold` to 110 pixels, that allows short swipes to scroll elements inside the tab and longer swipes to change the tab.

Could you please try this and do a short swipe?

```
<super-tabs config="{dragThreshold: 250, allowElementScroll: true}">
  <super-tab [root]="tab1Root"  icon="md-calendar"></super-tab>
  <super-tab [root]="tab5Root"  icon="ios-settings-outline"></super-tab>
</super-tabs>
```

**Comment by Srijan1702** [comment]
It's still not working, do I have to import something in my "tabs.ts" file?

**Comment by eduardoRoth** [comment]
@Srijan1702 

Could you post here your html code of the tab that you want your elements to scroll, please?

**Comment by Srijan1702** [comment]
Please look into following code as you asked, it was providing a horizontal scroll which was working fine before applying superTab module. Swipe down is working fine but swiping left or right is not scrolling the list but it changes the current tab.

```
<ion-col no-padding>
    <div class="scrollmenu">
       <div href="#home" *ngFor="let a of array" swipeAll (swipedown)="showFullCalendar()">
          <p class="noMargin">Jan</p>
          <p class="noMargin">Thu, 19</p>
          <p class="noMargin">3 Events</p>
       </div>
    </div>
</ion-col>
```

```
div.scrollmenu {
        background-color: whitesmoke;
        overflow: auto;
        white-space: nowrap;
        p{
            padding-top: 1px;
            padding-bottom: 1px;
        }
}
```

**Comment by Chethannp** [comment]
+1 same issue

**Comment by toventang** [comment]
try to add ion-content to subpages.

**Comment by Srijan1702** [comment]
@eduardoRoth @Chethannp 

Did you guys find any solution for this?

**Comment by duy205711** [comment]
Into super-tab i has a component to display content.  I try to style css for this component with overflow-y: scroll;

**Comment by pavillet** [comment]
Using 4.2.2 ion-scroll horizontal is working
BUT at the end of the horizontal scroll the page is changed ( ie the end of the list, no more items to horizontal scroll)
@eduardoRoth Is that normal behavior ? If so can it be avoided?

```
<ion-scroll padding scrollX="true" scrollY="false" class="x-scroller">
<div class="logo-round" *ngFor='let stuff of morestuffs'></div>
	</ion-scroll>
```

**Comment by sfaizanh** [comment]
@pavillet can you share some code, i have a same issue

**Comment by sfaizanh** [comment]
Figured it out
**tabs.ts**
```ts
config = {
	dragThreshold: 250,
	allowElementScroll: true
};
```
**tabs.html**
```html
<ion-content no-bounce>
  <super-tabs [config]="config">
    <super-tab [root]="page1"></super-tab>
    <super-tab [root]="page2"></super-tab>
    <super-tab [root]="page3"></super-tab>
    <super-tab [root]="page4"></super-tab>
  </super-tabs>
</ion-content>
```

**_Passing directly in attribute is not working_**
```html
<super-tabs config="{dragThreshold: 250, allowElementScroll: true}">
  <super-tab [root]="page1"></super-tab>
  <super-tab [root]="page2"></super-tab>
  <super-tab [root]="page3"></super-tab>
  <super-tab [root]="page4"></super-tab>
</super-tabs>
```

**Comment by eduardoRoth** [comment]
@sfaizanh, @Srijan1702 

I found what my mistake was; if you set the config in the HTML code, `config` attribute should be surrounded by square brackets for it to work:

```
<super-tabs [config]="{dragThreshold: 250, allowElementScroll: true}">
  <super-tab [root]="page1"></super-tab>
  <super-tab [root]="page2"></super-tab>
  <super-tab [root]="page3"></super-tab>
  <super-tab [root]="page4"></super-tab>
</super-tabs>
```

@pavillet , as implemented as it's right now, the component won't check if the list is on it's first or last element; it just checks if you have swiped the required pixels to change the tab; so, if while swiping you reach the start or end of the list and you keep going, it'll change tab

For now, you could increase the dragThreshold to something bigger so you could avoid this reach the start or end, and don't change tabs.

```
<super-tabs [config]="{dragThreshold: 300, allowElementScroll: true}">
   [...]
</super-tabs>
```

One small drawback is that for all your tabs, your user would need to swipe longer to change.

**Comment by Esom** [comment]
> Figured it out
> **tabs.ts**
> 
> ```ts
> config = {
> 	dragThreshold: 250,
> 	allowElementScroll: true
> };
> ```
> 
> **tabs.html**
> 
> ```
> <ion-content no-bounce>
>   <super-tabs [config]="config">
>     <super-tab [root]="page1"></super-tab>
>     <super-tab [root]="page2"></super-tab>
>     <super-tab [root]="page3"></super-tab>
>     <super-tab [root]="page4"></super-tab>
>   </super-tabs>
> </ion-content>
> ```
> 
> **_Passing directly in attribute is not working_**
> 
> ```
> <super-tabs config="{dragThreshold: 250, allowElementScroll: true}">
>   <super-tab [root]="page1"></super-tab>
>   <super-tab [root]="page2"></super-tab>
>   <super-tab [root]="page3"></super-tab>
>   <super-tab [root]="page4"></super-tab>
> </super-tabs>
> ```

this resolved my issues been thinking this was an ionic bug

**Comment by Esom** [comment]
scrollTabs no longer works

**Comment by agrinko** [comment]
No need to change config. Here is a solution from the docs: https://github.com/zyra/ionic2-super-tabs/#avoid-swipe-event

> Set avoid-super-tabs="true" attribute in HTML element for avoid swipe event. 
> Example when using the horizontal scroll bar inner super-tab Component

I also missed it in the readme initially, pehaps should be highlighted with red and bold 😄 

P.S: Consider closing the issue.

**Comment by utbhavesh** [comment]
public config = {
        dragThreshold: 250,
        allowElementScroll: true
    };
 <super-tabs [config]="config" *ngIf="arrEntity && arrEntity.length > 0">
</super-tabs>

I have used above code but I am not able to scroll the container horizontally

**Comment by che-azeh** [comment]
Here’s the actual solution:

```
  config: any = {
    allowElementScroll: true,
    avoidElements: true
  }
```
Note the “**avoidElements**” property. It tells Super Tabs to look and avoid elements with avoid-super-tabs attribute.
Now, on the element which scrolls alongside the super tab (ion-slides, or element with overflow-y: scroll for example), do:

`<ion-slides avoid-super-tabs="true">
`
[See the documentation](https://zyra.github.io/ionic-super-tabs/configuration/)
