### ISSUE TITLE
Hamburger menu inside supertabs

### ISSUE THREAD

**Issue by Chethannp** [zyra/ionic-super-tabs#258]
![approach](https://user-images.githubusercontent.com/7566931/35526967-3976bdea-054f-11e8-8284-a1d35a0e8070.png)

Clicking on the left hamburger menu should open the side menu. My code is below:

Guys I am seriously struggling on this since a week, am new to Ionic requesting you to please help me!!

HTML
=====================
```
<ion-
content>
    <super-tabs toolbarBackground="primary" scrollTabs="true" tabsPlacement="top" selectedTabIndex="0" indicatorColor="dark" (tabSelect)="onSegmentSelection($event)">
      <super-tab [root]="sideMenu" icon="menu"></super-tab>
      <super-tab [root]="menuRoot" title="You"></super-tab>
      <super-tab [root]="tab2Root" title="Financial Literacy" id="locationTab"></super-tab>
      <super-tab [root]="tab3Root" title="Healthy Reads" id="favouritesTab"></super-tab>
      <super-tab [root]="tab2Root" title="Topic1" id="locationTab"></super-tab>
      <super-tab [root]="tab3Root" title="Topic2" id="favouritesTab"></super-tab>
    </super-tabs>
</ion-content>
```

TS
======================
import { Component, ViewChild } from '@angular/core';
import { NavController, Nav } from 'ionic-angular';
import { Innertab1Page } from '../innertab1/innertab1';
import { Innertab2Page } from '../innertab2/innertab2';
import { Innertab3Page } from '../innertab3/innertab3';
import { AboutPage } from '../about/about';
import { SuperTabs } from 'ionic2-super-tabs';
import {SuperTabsController} from 'ionic2-super-tabs';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  sideMenu = AboutPage;
  tab2Root = Innertab2Page;
  tab3Root = Innertab3Page;
  menuRoot = Innertab1Page;
  @ViewChild(SuperTabs) superTabs: SuperTabs;
 
  constructor(public navCtrl: NavController, public nav: Nav) {
  }
  onSegmentSelection(eve){
    if(eve.index === 0){
      this.superTabs.slideTo(1);
    }    
  }
}

Thanks

**Comment by JoaoFMachado** [comment]
instead of <super-tab [root]="sideMenu" icon="menu"></super-tab> try <super-tab (ionSelect)="menuToggle()" icon="menu"></super-tab>.
Where menuToggle() is something like this:
menuToggle() {
      this.menuCtrl.toggle();
  }

**Comment by lincolnthree** [comment]
Neither of these options worked for me. It would be convenient if we could add custom tabs (that don't participate in the slide) at the beginning or end of the tab bar, but I'm sure it's more complicated than it sounds. As it stands right now I'm going to try playing with widths and absolute positioning to try to make it "look" like it. We'll see how it goes :)
