### ISSUE TITLE
How to modify the super-tabs-toolbar width?

### ISSUE THREAD

**Issue by CjoyHome** [zyra/ionic-super-tabs#259]
I want to modify super-tabs-toolbar width,does it contain this property?if modify  app.scss,All the pages of the supertabs will be modified。
![superpag](https://user-images.githubusercontent.com/26813427/35791811-c483e5a4-0a84-11e8-8319-0b7009e20b5f.png)

**Comment by Bobin56** [comment]
@CjoyHome  , i am also  stuck on this . Did u manage to solve this ?

**Comment by lincolnthree** [comment]
I would also love to know if there's a solution to this. Anyone get it figured out?
