### ISSUE TITLE
Tabs not changing manually (Ionic v3.9.2)

### ISSUE THREAD

**Issue by rodrigo-fonseca** [zyra/ionic-super-tabs#260]
Change Tabs by clicking in the tab itself [**OK**]
 Change Tabs manually (with my finger on cellphone or mouse on desktop) [**Not Working**]

Importing:

```
imports: [
    IonicModule.forRoot(MyApp),
    SuperTabsModule.forRoot(),
    BrowserModule,
    ComponentsModule,
    ServicesModule,
    HttpModule
  ]
```

```
 <super-tabs>
  <super-tab [root]="tab1Root" title="Passeio"></super-tab>
  <super-tab [root]="tab2Root" title="Esportivo"></super-tab>
</super-tabs>
```

How can I change my tabs manually (finger or mouse) like a slide? 

cheers

**Comment by saidcocenza** [comment]
@rodrigo-fonseca 
Did you manage to solve this problem? thanks for the reply.
