### ISSUE TITLE
ionic2-super-tabs this.navCtrl.parent.select(index) error not function

### ISSUE THREAD

**Issue by toem1234** [zyra/ionic-super-tabs#265]
When I click the link, link to  other tabs.

in ionic2 use
this.navCtrl.parent.select(index)

but  ionic2-super-tabs  not working

in ionic 2 i use

  gotoTreatment(){
    this.navCtrl.parent.select(1);
    
  }

Need help
Thank you

**Comment by eduardoRoth** [comment]
Could you please elaborate more on this error? What are you trying to do? Change tabs or navigate to other page within the parent page (the tabs container)?

If you're trying the second, you can get a reference to "App" and then set root:

```
this.app.getRootNav().setRoot('TreatmentPage');
```

One warning, `getRootNav` is going to be deprecated in Ionic next major release, so be careful.

In the other hand, if you're only trying to change tabs from code, read about SuperTabsController.

**Comment by anandraj9497** [comment]
Same issue here. @eduardoRoth Could you please explain the first approach?

**Comment by anandraj9497** [comment]
@eduardRoth,
The html code is given below. 
   <super-tabs tabsHighlight="true" tabsPlacement="top" [selectedTabIndex]="mySelectedIndex" >
    <super-tab [root]="contactsRoot" title="My Team" ></super-tab>
    <super-tab [root]="chatsRoot" title="Chats" ></super-tab>
    <super-tab [root]="callsRoot" title="Call Log" ></super-tab>
</super-tabs>

Here from the second tab (chat) when I click on a button i want the first tab to get activated.

Please note that tabs page is not the root module of the application.

Please help me with this

**Comment by eduardoRoth** [comment]
@anandraj9497 please use markdown syntax to prettify your comment.

You need to inject `SuperTabsController` in your chatsRoot component and from there call `slideTo`, something like this:

*TabsPage.html*
```
<super-tabs id="mainTabs" tabsHighlight="true" tabsPlacement="top" [selectedTabIndex]="mySelectedIndex" >
   <super-tab [root]="contactsRoot" title="My Team" >
   <super-tab [root]="chatsRoot" title="Chats" >
   <super-tab [root]="callsRoot" title="Call Log" >
</super-tabs>
```

*chatsRootPage.ts*
```
export class ChatsRootPage {
   constructor(private superTabs : SuperTabsController) {}

   goToContacts(){
      this.superTabs.slideTo(0, 'mainTabs'); // 0 is the index of contactsRoot tab and mainTabs is the id of your super-tabs component.
   }
}
```

That'll do the work.

**Comment by toem1234** [comment]
it working.
Thank you very much  

In ChildPage
import {SuperTabsController } from 'ionic2-super-tabs';
constructor(public navCtrl: NavController, public navParams: NavParams,
      private superTabs : SuperTabsController)

gotoAccount(){
    this.superTabs.slideTo(3,'mainTabs');
  }

**Comment by anandraj9497** [comment]
@eduardoRoth, Thank you very much for the reply. I am replying you via mobile device that's why. Can you clear one more doubt in this thread?

**Comment by eduardoRoth** [comment]
Yeah, sure @anandraj9497 , what's it?

**Comment by eduardoRoth** [comment]
@anandraj9497 could you explain more what are you trying to achieve?

**Comment by anandraj9497** [comment]
@eduardoRoth , consider
```
<super-tabs id="mainTabs" tabsHighlight="true" tabsPlacement="top" [selectedTabIndex]="mySelectedIndex" >
   <super-tab [root]="contactsRoot" title="My Team" >
   <super-tab [root]="chatsRoot" title="Chats" >
   <super-tab [root]="callsRoot" title="Call Log" >
</super-tabs>
```
when I navigates from say first tab to any inner pages the tabs should not be displayed there.
