### ISSUE TITLE
FEATURE: Remove Toolbar and replace with Slides "Pager" 

### ISSUE THREAD

**Issue by T-Munyaka** [zyra/ionic-super-tabs#266]
Hi there,

Thanks for the awesome plugin. I'm working on a project were I would like to replace the toolbar with a pager indicator when navigating through the various tabs. How can I possibly implement this? I have successfully removed the toolbar as per your documentation, but now I want to show a "pager" to indicate that you can swipe left or right to navigate to the other pages.

This 'pager' element I'm referring to is part of the ion-slides options.

Thanks!
I've linked a reference of the feature below.
[https://ibb.co/m62ZO7](url)

**Comment by ihadeed** [comment]
Next version will allow you to remove the toolbar. We won't have a pager though since that's definitely out of the project scope.
