### ISSUE TITLE
How can i use virtual scroll  inside super tab????????? 

### ISSUE THREAD

**Issue by Abdullahincep** [zyra/ionic-super-tabs#267]
Hello i am trying to use virtual scroll inside super tab but it display blank.If  add another tab than content will be display but not showing on first tab.

 here is my ts code

```
 items:any;

 constructor( ){
    this.items = [];
    for(let i = 0; i < 500; i++){
          let item = { title: 'Title'};
          this.items.push(item);
    }
```

here is super tab html 
```

 <super-tabs scrollTabs  (tabSelect)="onTabSelect($event)"   style="height:100%;" >
    <super-tab  [root]="storepartials" [title]="'allCount'"     id="1"    ></super-tab>
</supertabs>
```

and tab content page html 
```

<ion-list [virtualScroll]="items" [approxItemHeight] ="'300px'">

   <ion-item *virtualItem="let item">
     
       <h2>{{item.title}}</h2>

   </ion-item>

</ion-list>
```

ionic version : 3.19.0

console does not show any error

![virtual](https://user-images.githubusercontent.com/24888735/36209075-bae06c50-11c0-11e8-8ad2-8399cd2cb836.PNG)

please help if anybody know how to use virtual scroll inside super tab or only tab thanks.

**Comment by touficzayed** [comment]
Hi,

I have the exact same problem... using Ionic 3 latest version with angular 4.

**Comment by eduardoRoth** [comment]
@Abdullahincep, @touficzayed ;

I had this problem, the thing is that the container for the virtual scroll has a height of 0, so it seems to be hidden, try setting a defined height in pixels or viewport related and it'll show.

So far I haven't found a way to set it to fill the rest of the page.

**Comment by Shtibel** [comment]
Any news on this problem?
