### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this.initialCoords.x')

### ISSUE THREAD

**Issue by Maistho** [zyra/ionic-super-tabs#276]
Got this error in my logs today, seems to be located in [this line](https://github.com/zyra/ionic2-super-tabs/blob/ca62985d70749140a0e1ae48e9fdb003f1eb67c1/src/super-tabs-pan-gesture.ts#L133) but I'm not quite sure when it triggers or how to reproduce.

Any ideas how `initialCoords` could become undefined there? I will try to see if I can get a consistent reproduction to help debugging it.

**Comment by eduardoRoth** [comment]
Hi @Maistho , sometimes I get this error when the app hasn't finished loading completely and I start swiping between tabs. I haven't checked the reason this happens, but I guess it could be related with the tabs not being render completely when I start moving between them.
