### ISSUE TITLE
hidden(style.display = "none") super-tabs couldn't calculate indicator width correctly

### ISSUE THREAD

**Issue by jiminsc** [zyra/ionic-super-tabs#278]
hidden(style.display = "none") super-tabs couldn't calculate indicator width correctly because of the nativeElement's offsetWidth is 0

**Comment by eduardoRoth** [comment]
Hi @jiminsc , could you please provide more detail of your problem, including code and screenshots of your problem?

Thanks

**Comment by jiminsc** [comment]
@eduardoRoth thanks for your reply.
here is my code
```javascript
<ion-content>
      <super-tabs [style.display]='show?"block":"none"'>
          <super-tab [root]='page1' [rootParams]='param' title='page1'></super-tab>
          <super-tab [root]='page2' [rootParams]='param' title='page2'></super-tab>
      </super-tabs>
</ion-content>
```
when style.display changed from "none" to "block"，the page rendered as below
![image](https://user-images.githubusercontent.com/8499767/37573693-a78e6cd4-2b55-11e8-9ccc-fd41e6921ff0.png)
the indicator didn't rendered, when I resize the window, the indicator showed up
![image](https://user-images.githubusercontent.com/8499767/37573899-7d34a604-2b57-11e8-8d74-4f6d6716a3ab.png)

I think in method setFixedIndicatorWidth of super-tabs class
```javascript
  private setFixedIndicatorWidth() {
    if (this.scrollTabs || !this._isToolbarVisible) return;
    // the width of the "slide", should be equal to the width of a single `ion-segment-button`
    // we'll just calculate it instead of querying for a segment button
    this.toolbar.setIndicatorWidth(this.el.nativeElement.offsetWidth / this._tabs.length, false);
  }
```
> **this.el.nativeElement.offsetWidth** get 0 when the super-tabs is hidden by setting display to "none"

and here is my provisional solution

```javascript
  ngAfterViewChecked(){
    this.tabs.resize();
  }
```

**Comment by eduardoRoth** [comment]
@jiminsc instead of setting style.display, can you use the `showToolbar`function instead?

https://github.com/zyra/ionic2-super-tabs#showtoolbar

## showToolbar
```
showToolbar(show: boolean, tabsId?: string): void
```
Show/hide toolbar
- show: boolean that indicates whether to show the toolbar
- tabsId: the unique ID for parent SuperTabs. Defaults to the first instance registered in memory.

**Comment by jiminsc** [comment]
@eduardoRoth I want to hide the whole SuperTabs including everything inside for some specific reason, not just the toolbar

**Comment by eduardoRoth** [comment]
@jiminsc So a user enters the page and is shown something else and after a tap (or some other event), the tabs are shown?

**Comment by jiminsc** [comment]
@eduardoRoth yes, in my case, loading information is shown instead of the empty tabs at first, when the request finished ,the tabs rendered with data are shown
