### ISSUE TITLE
ngIf on <super-tab>

### ISSUE THREAD

**Issue by lcaprini** [zyra/ionic-super-tabs#280]
Hi,
first of all thank you for this wonderful plugin. :)

I have a page with a superTabs with 3 tabs, but one of them (the 2nd one) i would like to take hidden while user is not logged, and turn on when user login.

I'm trying this:
```html
<ion-content>
    <super-tabs #myST>
        <super-tab [root]="tab1Root" title="Tab1"></super-tab>
        <super-tab [root]="tab2Root" title="Tab2"></super-tab>
        <super-tab [root]="tab3Root" title="Tab3"></super-tab>
    </super-tabs>
</ion-content>
```
```typescript
@ViewChild('myST') superTabs: SuperTabs;
    userIsAuthenticated: boolean = false;
    tab1Root = Page1;
    tab2Root = Page2;
    tab3Root = Page3;

    ionViewDidEnter(){
        // Simulate delay for user login
        setTimeout(() => {
            this.userIsAuthenticated = true;
            // Force resize to update indicator
            setTimeout(() => {
                this.superTabs.resize();
            }, 0);
        }, 2000);
    }
```
After the (fake) login the `tab2Root` super-tab appears correctly between `tab1Root` and `tab3Root`, but in the toolbar the `Tab2` title appears as last, after the `Tab3`.

Is possible to fix it or make some workaround?

Thank you.
--Luca

**Comment by eduardoRoth** [comment]
@lcaprini at the moment `SuperTabs` doesn't handle well dynamically created or shown tabs, if your login page is not inside the SuperTabs component, you can redirect after login to another page that already has your three tabs:

1. User enters app, only tabs 1 & 3 are shown.
2. User taps on `login` button
3. App opens modal or sets root for login page
4. User logins successfully in the app
5. App sets root for page with tabs 1, 2 & 3; and the closes modal (if login was a modal)

**Comment by lcaprini** [comment]
@eduardoRoth Thank you for your replay.
Unfortunately every tab in the page makes some async HTTP calls so I wouldn't recreate them.
There is a way to edit your `resize()` method to print the tabs in the right order?

**Comment by lcaprini** [comment]
@eduardoRoth Another solution may be edit your plugin and add the `[show]` option for `super-tab` component in the same way on the original ionic tab (https://ionicframework.com/docs/api/components/tabs/Tab/#input-properties).
What do you think?

Thanks

**Comment by nelutzu91** [comment]
Hello @eduardoRoth,
any news on this?
I am totally agree with the last comment of @lcaprini about [show] attribute from default ion-tab component.

**Comment by Simbaclaws** [comment]
I see inside the stencil rewrite features that this is done?
However when I import the latest version there is no such [show] attribute available for either <super-tab-button> or for <super-tab>

What is the current progress of this?
