### ISSUE TITLE
Deep linking with ionic2-super-tabs

### ISSUE THREAD

**Issue by chintankshah** [zyra/ionic-super-tabs#282]
Hi,

I'm using ionic2-super-tabs and I'd like to get deep linking to all my tabs. Currently, I see the URL to the tab getting generated randomly. It follows the pattern '/nav' followed by '/nx' where x is a random number like '/n5' or '/n6' and so on. 

Is there a way I can replace this tab URL with something I pass in navParams? Something like IonicPage's segment property.

I tried adding segment to the root page that loads in <super-tab> but that simply gets added after /nav/nx part.

**Parent Component:**

```
<super-tabs>
    <super-tab 
      *ngFor="let tab of tabs; let i = index" 
      [root]="myTabPage" 
      [rootParams]="{tabId: tab.id}">
    </super-tab>
</super-tabs>
```

**Tab Component:**

```
@IonicPage({
  segment: "tab/:tabId"
})
@Component({
  selector: 'my-tab',
  templateUrl: 'my-tab.html',
})
export class MyTabPage { }
```

And this gives me URL like, 

http://localhost:8100/#/home/1/nav/n5/tab/1
http://localhost:8100/#/home/1/nav/n6/tab/2
http://localhost:8100/#/home/1/nav/n7/tab/3

What I'm looking here is something like http://localhost:8100/#/home/1/tab/1

Thanks.

**Comment by Eraldo** [comment]
Same here.

**Comment by peterlai107** [comment]
same here.
