### ISSUE TITLE
How to send data from parent page to child pages while using ionic-super-tabs

### ISSUE THREAD

**Issue by shri1983** [zyra/ionic-super-tabs#283]
Hi,
Thanks in advance.
I am using ionic-supr-tabs @4.1.4 in ionic3 and stuck on an issue where i have to send data from parent page(where super tabs defined and populate three pages via an array) to child pages. 
Please help me out on this issue. Almost whole day i have spend on it and still there is no solution.

**Comment by kimi21** [comment]
this may help #157
