### ISSUE TITLE
swiping content elements

### ISSUE THREAD

**Issue by Eraldo** [zyra/ionic-super-tabs#290]
I have a custom element that is listening to the `(swipe)` event.
And with the default settings that does work, however I does two things at once:
1. Trigger the element swipe.
2. Change the tab.

How can I swipe my element without changing the tab?

I tried to use `allowElementScroll` and `e.preventDefault()` with no success.
Also calling `this.superTabs.enableTabSwipe(false)` did not help.

Ideas?

**Comment by eduardoRoth** [comment]
@Eraldo , could you post your code here so I could take a look at it?

allowElementScroll increases the drag length (in pixels) before firing the change tab event, maybe your swipe is longer than this limit and starts changing your tab. Try also adding `dragThreshold` param and increase it maybe to 350 and give it a try.
