### ISSUE TITLE
Header Overlapping 

### ISSUE THREAD

**Issue by ymcewen** [zyra/ionic-super-tabs#292]
Hi, I've been going crazy over the past few days. 

I created a simple app with the super tab under the header. It loads looks fine in the browser and even works well on the device (tested iOS iPhone X and iPhone 7)

BUT after testing the next day, the header seems to overlap the supertab. Its the strangest thing. 

Now when I remove the platform and re-add it, it does the same.

I'm not sure how to solve this but it's driving me mad.

I decided to follow a tutorial online to make sure I was doing everything right but not only is it happening in my app, its also happening in the demo app I created using the tutorial.

Attached is how it was displaying and then how it is now displaying. (screenshots from iPhone X)

Any help is much appreciated.
![img_3274](https://user-images.githubusercontent.com/5821896/39053229-51ddbf1e-44a6-11e8-8b65-1c72585e41bc.jpeg)
![img_3273](https://user-images.githubusercontent.com/5821896/39053230-539dd65e-44a6-11e8-9f5c-2996e5fe04ba.jpeg)

**Comment by ymcewen** [comment]
Actually, Ive noticed, if I tap on about (on the bottom tab) then back to home, the content displays correctly.

**Comment by ymcewen** [comment]
To add a bit more context to the bug here is some more info:

**Comment by davym144** [comment]
This is happening on iPhone 8 too but strangely it work as expected on 6s and IPhone X.

Any help please

**Comment by ymcewen** [comment]
It’s been a while now, but as a work around what I did was call this.content.resize();  in ionViewDidEnter() three times. After 300th of a second, 3 seconds and 30 seconds. The view will only change if the tabs are hidden. 

It's an ok little work around.

**Comment by davym144** [comment]
This resolved the issue on iPhone 8 but the menu has disappeared on the iPhone X. 

Thanks for the reply though.
