### ISSUE TITLE
ionViewWillEnter and none of the other life cycle hooks of ionic for a super tab is called when naviagated back to that tab from a child view using navCtrl.pop().

### ISSUE THREAD

**Issue by bergist** [zyra/ionic-super-tabs#295]
I am navigating to another page from a super tab using rootNavCtrl. But when I am coming back to the tab using navCtrl.pop() ionViewWillEnter and none of the other life cycle hooks of ionic for a super tab is called.

**Comment by eduardoRoth** [comment]
@bergist how many tabs do you have?

`SuperTabs` preloads the next and previous tab when it enters a tab, so it can show a smooth transition between tabs; so any `ionViewWillLoad` or `ionViewDidLoad` events will just load once before you enter the page (differently as if you use traditional navigation where it's only loaded when you push it to the nav controller)

**Comment by bergist** [comment]
I Have two tabs.
**HomePage.ts (where the super tabs template is created.)**
export class HomePage {
  cla="0"

  @ViewChild(SuperTabs) superTabs: SuperTabs;

  page1: any = 'Page1Page';
  page2: any = 'Page2Page';
  page3: any = 'Page3Page';

  showIcons: boolean = false;
  showTitles: boolean = true;
  pageTitle: string = 'Full Height';

  constructor(public navCtrl: NavController, private navParams: NavParams, private superTabsCtrl: SuperTabsController) { }

  onTabSelect(tab: { index: number; id: string; }) {
    console.log(`Selected tab: `, tab);
  }
}

**Home.html**
<ion-header no-shadow no-border>
  <ion-navbar color="dark" >
    <button ion-button menuToggle color="yellow">
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title>{{ pageTitle }}</ion-title>
  </ion-navbar>
</ion-header>
<ion-content no-bounce>
  <super-tabs  id="mainTabs" [config]="{ sideMenu: 'left' }" scrollTabs toolbarColor="light" toolbarBackground="dark" indicatorColor="secondary" badgeColor="yellow" (tabSelect)="onTabSelect($event)">
    <super-tab [swipeBackEnabled]="false" [root]="page1" [title]="showTitles? 'Berg' : ''" [icon]="showIcons? 'home': ''" id="page1"></super-tab>
    <super-tab [root]="page2" badge="5" [title]="showTitles? 'Trending' : ''" [icon]="showIcons? 'trending-up' : ''" id="page2"></super-tab>
    
  </super-tabs>
</ion-content>

**Page1.ts**
export class Page1Page {
  visible='true';
  rootNavCtrl: NavController;

  constructor(public navCtrl: NavController, public navParams: NavParams, private loadingCtrl: LoadingController,
    private superTabsCtrl: SuperTabsController) {
    this.rootNavCtrl = navParams.get('rootNavCtrl');
  }

  ionViewWillLoad() {
    console.log('[1] will load fired');
  }

  ionViewDidLoad() {
    console.log('[1] did load fired');
  }

  ionViewWillEnter() {
    console.log('[1] will enter fired');
    this.superTabsCtrl.showToolbar(true,'mainTabs')
    this.visible='true';
  }

  ionViewDidEnter() {
    console.log(this.navCtrl.getActive().name)
    console.log('[1] did enter fired');
  }

  pushPage(localNavCtrl: boolean = false) {
    if (localNavCtrl) {
      this.superTabsCtrl.showToolbar(false,'mainTabs')
      this.visible='false';
      this.navCtrl.push('PageToPushPage');
    } else {
      this.rootNavCtrl.insert(1,'PageToPushPage');
    }
  }

}
**# Page1.html**
<ion-content padding>
   <h1>
     This is the first page
   </h1>
  <button ion-button mode="ios" round (click)="pushPage()">Push page</button>
</ion-content>

# **Page2.ts**
export class Page2Page {
  visible=true;
  content:any={tag:"this is bergin here"};
  rootNavCtrl:NavController
  constructor(public navCtrl: NavController, public navParams: NavParams,
              private superTabsCtrl: SuperTabsController) { 
    this.rootNavCtrl = navParams.get('rootNavCtrl');
    console.log("blah")
  }

  ionViewWillLoad() {
    console.log('[2] will load fired');
    
  }

  ionViewDidLoad() {
    console.log('[2] did load fired');
  }

  ionViewWillEnter() {
    console.log('[2] will enter fired');
    debugger;
    setTimeout(()=>{
      debugger;
      this.content={}
        this.content.tag="blah blah"
        console.log(this.content,'voila')
    },3000)
    console.log(this.content.tag)
  }

  ionViewDidEnter() {
    console.log('[2] did enter fired');
  }
  pushPage(localNavCtrl: boolean = false) {
    if (localNavCtrl) {
      this.superTabsCtrl.showToolbar(false,'mainTabs')
      this.visible=false;
      this.navCtrl.push('PageToPushPage');
    } else {
      this.rootNavCtrl.push('PageToPushPage');
    }
  }
}

# **Page2.html**
<ion-content padding>
  <h1>
    {{content.tag ||async}}
  </h1>
  
  <button ion-button mode="ios" round (click)="pushPage()">Push page</button>
</ion-content>

**# PagetoPush.ts**
export class PageToPushPage {

  constructor(public navCtrl: NavController, public navParams: NavParams, private viewCtrl:ViewController) { 
    console.log(this.navCtrl.getActive().name)
    console.log(this.navCtrl.indexOf(this.navCtrl.getActive()))
  }

  goback(){
    this.navCtrl.pop();
  }
}

# **Pagetopush.html**
<ion-header>

  <ion-navbar>
    <ion-title>PageToPush</ion-title>
  </ion-navbar>

</ion-header>

<ion-content padding>
  
  <button ion-button (click)="goback()">go back</button>
</ion-content>


Now if you run this, swipe to the second tab i.e. page2 and wait for three seconds you will find the heading changed as I have set a timeout. Now if you navigate from there to pagetopush Page using the button present there.
and then navigate back to page 2 by pressing the goback button present in page to push you will find that the ionViewWillEnter is not called hence the timeout function is not called.

I hope you understood what I am trying to say. I understood what you meant when you said ionViewWillLoad & ionViewDidLoad is called, but I am using ionViewWillEnter here.

**Comment by eduardoRoth** [comment]
@bergist I can't replicate your error,

When I enter your app I'm shown the two tabs and events fire correctly:
![image](https://user-images.githubusercontent.com/5419161/39255448-2a03d38c-4872-11e8-9833-a3669a973ba4.png)

If I push the button there I'm shown the `PageToPush` page:
![image](https://user-images.githubusercontent.com/5419161/39255486-44fce426-4872-11e8-8abb-0ab56b3b1798.png)

After that, if I click on `Go Back` button I go back to `Tabs` page and automatically shown the second tab
![image](https://user-images.githubusercontent.com/5419161/39255526-64a52536-4872-11e8-84a8-b5fb7d0f31b9.png)

And then the title changes
![image](https://user-images.githubusercontent.com/5419161/39255556-7066f232-4872-11e8-93e2-31739b9220a2.png)

----
The only scenario when this doesn't happen is when you click on the "back button arrow", and thats because - I think - how Ionic works as the `go back arrow button` represents that nothing was changed and you only went back.

**Comment by eduardoRoth** [comment]
@bergist Could you run an `ionic info` command in your project folder and paste the results:

![image](https://user-images.githubusercontent.com/5419161/39256291-25a5d810-4874-11e8-97f3-ba60a5b6b102.png)

**Comment by ArtKuz** [comment]
+1
