### ISSUE TITLE
tab click event

### ISSUE THREAD

**Issue by KishoreKoushik** [zyra/ionic-super-tabs#296]
what is the function that is fired when a tab is clicked. I tried (click) event, but is does not work.

**Comment by saidcocenza** [comment]
good post.! and if I want to activate the slider in the supertabs and not by console as I do? thanks for the reply.!

**Comment by eduardoRoth** [comment]
@saidcocenza could you give me more detail about what you're trying to do, please?

**Comment by saidcocenza** [comment]
thanks for responding quickly, well I want to slide the tab but I do it is by console I was trying with this.supertabs (('Tab selected', 'Index:' + ev.index, 'Unique ID:' + ev.id); and I could not, any suggestions?

**Comment by saidcocenza** [comment]
also try with 

onTabSelect(eve){
if(eve.index === 0){
this.superTabs.slideTo(1);
}
}

**Comment by eduardoRoth** [comment]
@saidcocenza you want to slide to the second tab immediately or at what time? I'm trying to figure what you expect to do. 

If you want to automatically go to the second tab after a period of time, do this:

```
ionViewDidEnter(){
   setTimeout(() => {
      this.superTabs.slideTo(1);
   }, 2500);
}
```

**Comment by saidcocenza** [comment]
Thanks again, what I want and I have not been able to do is to slide to the other page manually and I can visualize it in my chrome browser, as it is going, I do it with your code but in console

  onTabSelect(ev: any) {
    console.log('Tab selected', 'Index: ' + ev.index, 'Unique ID: ' + ev.id);
  }


and what I want is to slide the pages as if the app is already finished, thank you very much again for the help provided.

**Comment by saidcocenza** [comment]
@eduardoRoth 
try to do this

allowElementScroll: "true"             and
scrollTabs="true"


and I can not get the supertabs to slide, so will there be any way to make the tab title slip?

**Comment by saidcocenza** [comment]
@eduardoRoth 

I did this 

https://github.com/zyra/ionic2-super-tabs/issues/256

and nothing as you comment only by console
