### ISSUE TITLE
Support for tabsLayout?

### ISSUE THREAD

**Issue by maheshwarishivam** [zyra/ionic-super-tabs#306]
Hi,

How do I use `tabsLayout` property from [official Tabs Component](https://ionicframework.com/docs/api/components/tabs/Tabs/#input-properties).

Possible layouts are:

`icon-top`, `icon-start`, `icon-end`, `icon-bottom`, `icon-hide`, `title-hide`.

I specifically want to use `icon-start` layout. How to achieve it?

**Comment by magic-77** [comment]
You can't use it from other Component.
Use the build in Functions/Properties

https://github.com/zyra/ionic2-super-tabs#usage

**Comment by magic-77** [comment]
Did you read the Usage?
You can playaround with the Demo, to see what is possible
https://github.com/zyra/ionic2-super-tabs-example

**Comment by maheshwarishivam** [comment]
@magic-77 : Yes I read the usage. I just wanted to know if it's supported or not.

I guess that it's not supported.
