### ISSUE TITLE
Property 'parent' in type 'SuperTabs' is not assignable to the same property in base type 

### ISSUE THREAD

**Issue by magic-77** [zyra/ionic-super-tabs#310]
Updating Typescript to 2.9.1 throws this Error
Going back to Typescript 2.8.1 or 2.8.3 super-tabs works as expected

```
[20:34:33]  typescript: node_modules/ionic2-super-tabs/dist/components/super-tabs.d.ts, line: 153 
            Property 'parent' in type 'SuperTabs' is not assignable to the same property in base type 
            'NavigationContainer'. Type 'NavControllerBase' is not assignable to type 'NavController'. Types of property 
            'config' are incompatible. Type 
            'import("/home/mdev/_projects/myspaeti/web/html/source-new-marek/node_modules/ionic-angular/umd/co...' is 
            not assignable to type 
            'import("/home/mdev/_projects/myspaeti/web/html/source-new-marek/node_modules/ionic-angular/config...'. 
            Types have separate declarations of a private property '_c'. 

     L153:  parent: NavControllerBase;
     L154:  constructor(parent: NavController, viewCtrl: ViewController, _app: App, el: ElementRef, rnd: Renderer2, superTabsCtrl: SuperTabsController, linker: DeepLinker, domCtrl: DomController, _plt: Platform);

```

**Comment by Dharma404** [comment]
It worked. Thanks @magic-77

**Comment by tverilytt** [comment]
I am getting the same with Ionic 3.9.2...

Cheers
-jo

**Comment by tverilytt** [comment]
I got the error when compiling in Sublime Text. It had the TypeScript plugin v3.0.1 installed. Whilst the Ionic project had TypeScript 2.6.2.

After installing TypeScript globally (npm install -g typescript@2.6.2), and adding this line to Sublie Text Settings -~ User, the error is gone in Sublime Text:
"typescript_tsdk": "/usr/local/lib/node_modules/typescript/lib"

The plugin version settings is described here:
https://packagecontrol.io/packages/TypeScript

-----
Note: Using different versions of TypeScript
This plugin can be configured to load an alternate version of TypeScript. This is typically useful for trying out nightly builds, or prototyping with custom builds. To do that, update the Settings - User file with the following:

"typescript_tsdk": "<path to your folder>/node_modules/typescript/lib"
-----

Cheers
-jo

**Comment by pipoa** [comment]
+1
typescript 2.8.3 is ok, however 2.9.2 get this error message.
