### ISSUE TITLE
How to hide the names of the unselected tabs?

### ISSUE THREAD

**Issue by reuseman** [zyra/ionic-super-tabs#318]
Hello everyone, I was wondering how can I achieve the following effect. In the classic tabs offered by ionic there are the CSS variable to play with. Thank you in advance

![Effect to achieve](https://media.giphy.com/media/fnMMWzxjttiGLecmpQ/giphy.gif)

**Comment by eduardoRoth** [comment]
Use the following CSS

```
super-tab-button:not(selected) {
        opacity: 0.6; // if you want to set transparenty for items not selected
        .title {
            display: none !important;
        }
        ion-icon {
            margin-top: 6px !important; // you'll have to check the amount of pixels needed to vertically center your icons
        }
}
```

**Comment by reuseman** [comment]
@eduardoRoth For some reason, the text become invisible even for the selected tab. I even tried on a blank project but I can't figure out why
