### ISSUE TITLE
this.nav.getActiveChildNav(...).select is not a function

### ISSUE THREAD

**Issue by sachinGAcharya** [zyra/ionic-super-tabs#321]
I am developing an app using ionic 3 . My side menu has a homepage and the upon opening the tab it will by default land to homepage.I have one button on homepage on click of that it will go to tabs page. I have implemented that using superlabs, Everything is working nice. Except from tabspage, When  I click on home which is in side menu ,I get the following error,

this.nav.getActiveChildNav(...).select is not a function

please help me.
Thanks.

**Comment by kalyan312** [comment]
I faced same issue. did you found any solution.

**Comment by sachinGAcharya** [comment]
In my case I had put  { title: 'Dashboard', pageName: 'DashboardPage',tabcomponet:'Homepage' }
I removed tab component then it started working,

**Comment by ChrizC** [comment]
I've submitted a fix for this in PR #323 - if you could show support for that PR we can get this properly fixed

**Comment by dayaki** [comment]
@ChrizC I think the PR is merged but am still having the same error, am using v5.0.2. @sachinGAcharya are you able to find a solution?
