### ISSUE TITLE
super-tab margins

### ISSUE THREAD

**Issue by Nick-lab** [zyra/ionic-super-tabs#330]
hey what is the variable of total length to slide for each tab and can that be modified to include margin offsets? i want to have a sorta no mans land in between pages for visual effect.

in this image the lime green is the margins between pages the fist page is fine but the offset is compounded with each page swiped left
![image](https://user-images.githubusercontent.com/32395162/44466766-20271880-a5ef-11e8-81e3-cf1bf2567906.png)

![image](https://user-images.githubusercontent.com/32395162/44466842-464cb880-a5ef-11e8-92de-7686f640efbf.png)

**Comment by ihadeed** [comment]
So you have margins between the `super-tab` elements, so when the user swipes between the tabs there's spacing between the tabs?

If so, this isn't something we wish to support as it's not a common UX pattern and it doesn't follow the material design specs. Feel free to fork the repo & modify the code for your needs.

**Comment by aleygues** [comment]
Hi, using CSS padding on slide content (maybe `ion-slide`) should do the trick!

**Comment by Nick-lab** [comment]
@ihadeed well thanks for the reply, but i have no clue where to start with creating or changing plugins and how to implement them. thanks for the help though.

**Comment by Nick-lab** [comment]
@aleygues can i have the pages keep the View life cycles with `ion-slide` ?
