### ISSUE TITLE
Code compilation

### ISSUE THREAD

**Issue by sckumar** [zyra/ionic-super-tabs#333]
Not able to compile source code of master branch.

<img width="1280" alt="screen shot 2018-09-05 at 10 22 21 am" src="https://user-images.githubusercontent.com/7487076/45071784-98183700-b0f5-11e8-85a4-16ebb16773e6.png">

**Comment by heidji** [comment]
downgrade your typescript version. it helps solve many problems.
i believe version 2.4.0 works fine
