### ISSUE TITLE
swipe doesnt work with webview in tabs

### ISSUE THREAD

**Issue by babinchicken** [zyra/ionic-super-tabs#335]
i Have multiple tabs in my app ,tabswipe doesnt work ,when there is webview in my tab. it works perfectly fine when their is no webview int it, 

Also i want tabslide with 3 fixed tabs in my main toolbar which is also not working

**Comment by ihadeed** [comment]
Could you please elaborate on the issues you're having.

- What do you mean by having a webview in a tab?
- Provide an example of the "tabslide with 3 fixed tabs in my main toolbar" part

Also, if something doesn't work with Ionic's regular tabs, it's most likely a core issue that we cannot resolve at this moment until we rewrite the project with a different approach.

**Comment by babinchicken** [comment]
I have 10 super tabs, everypage have webview completely filled in it ..Area where there is webview it wont take any swipe events, not for sidemenu or tab swap ..

simply said ,my super tabs page.html have iframe for a webview
