### ISSUE TITLE
[ Question ] Is there any way to use this component in the same way as the ion-segment?

### ISSUE THREAD

**Issue by ronaiza-cardoso** [zyra/ionic-super-tabs#34]
Fist of all, this project is a great work! Thanks a lot for that.

Here is my question:

I start to think if there is a way of use this compent using on `<ion-segment>` way instead of create page for each page. If yes, would be of great help.

**Comment by ihadeed** [comment]
It's not possible at the moment, but it's possible to do something like that.  I will look into it.

**Comment by niravjadatiya** [comment]
let us know if is there any way available to use segment right now because in our project we use segment in all pages and it's not possible to create separate pages
