### ISSUE TITLE
[Request] Hide navbar and or tabs when scrolling

### ISSUE THREAD

**Issue by chriswatt** [zyra/ionic-super-tabs#351]
See the material design example here - https://material.io/design/components/tabs.html#behavior

On that page scroll down to the `Scrolling` section, there are 2 different videos. The first shows hiding only the navbar when scrolling a tab, the second shows hiding both the navbar and tabs when scrolling.

There are various ways to hide the navbar when scrolling a single page, one example is here - https://medium.com/@gregor.srdic/ionic3-hidding-header-on-footer-on-content-scroll-15ab95b05dc5

However these methods don't work with super-tabs.

**Comment by heidji** [comment]
i am working on the said project. it is still in development atm and will get improved soon. please feel free to try it out: [repo](https://github.com/heidji/ionic3-hidenav)

**Comment by heidji** [comment]
@chriswatt Hey, The [0.0.9](https://www.npmjs.com/package/ionic3-hidenav) I uploaded yesterday works pretty well IMO, did you try it out? 
Any feedback would be helpful..

**Comment by ihadeed** [comment]
Closing in favour of #25
