### ISSUE TITLE
How to disable super-tabs(make them unclickable) like in ion-tab's enabled "false "? 

### ISSUE THREAD

**Issue by jantoktosunov** [zyra/ionic-super-tabs#358]
How to disable super-tabs(make them unclickable) like in ion-tab's enabled "false "? 
`<ion-tab [root] = "tab5" tabIcon="cart"  enabled = "false"></ion-tab> `

![image](https://user-images.githubusercontent.com/9590595/51608949-28c2a880-1f19-11e9-814c-8f230b2e2377.png)

**Comment by indrapalijama** [comment]
> How to disable super-tabs(make them unclickable) like in ion-tab's enabled "false "?
> `<ion-tab [root] = "tab5" tabIcon="cart" enabled = "false"></ion-tab> `
> 
> ![image](https://user-images.githubusercontent.com/9590595/51608949-28c2a880-1f19-11e9-814c-8f230b2e2377.png)

how to do this? why is this issues got closed?
