### ISSUE TITLE
How to change tab root programatically?

### ISSUE THREAD

**Issue by bot101** [zyra/ionic-super-tabs#363]
I am working on a page that loads a super-tab, and clicking a button is supposed to change the component attached to one of the tab's [root]. I have tried changing the ionic page component without any changes happening and can't seem to find any similar solution on the internet.

```
//Originally defined like this
public tab1 = Page1Page; 
public tab2 = Page2Page;
```

HTML:
```
<super-tabs #superTab (tabSelect)="onTabSelect($event)" no-border selectedTabIndex="0"  indicatorColor="yellow" class="sub-tabs">
    <div class="cll">
      <super-tab [root]="tab1" title="Page 1" icon="balance"></super-tab>
    </div>
    <div class="cll">
      <super-tab [root]="tab2" title="Page 2"  icon="save"></super-tab>
    </div>
  </super-tabs>
```
now, I would like to change component aattached to `tab2`:

```
changeTabPage(){
   this.tab2= Page3Page; //Not working
}
```

Any solution?

**Comment by heidji** [comment]
```typescript
@ViewChild(SuperTabsComponent) tabs: SuperTabsComponent;

...
this.tabs.slideTo(0);

```

**Comment by ihadeed** [comment]
It's not possible with the current stable version. The next release will allow dynamic tabs and much more customisation. Stay tuned.
