### ISSUE TITLE
An interface may only extend a class or another interface Ionic-4 compile failed

### ISSUE THREAD

**Issue by rajkhan91** [zyra/ionic-super-tabs#373]
[ng] ERROR in node_modules/@ionic-super-tabs/angular/dist/directives/proxies.d.ts(3,43): error TS2312: An interface may only extend a class or another interface.
[ng] node_modules/@ionic-super-tabs/angular/dist/directives/proxies.d.ts(3,61): error TS2344: Type '"SuperTab"' does not satisfy the constraint '"IonIcon" | "IonActionSheetController" | "IonActionSheet" | "IonAlertController" | "IonAlert" | "IonAnchor" | "IonApp" | "IonAvatar" | "IonBackButton" | "IonBackdrop" | "IonBadge" | ... 86 more ... | "IonVirtualScroll"'.
[ng] node_modules/@ionic-super-tabs/angular/dist/directives/proxies.d.ts(9,49): error TS2312: An interface may only extend a class or another interface.
[ng] node_modules/@ionic-super-tabs/angular/dist/directives/proxies.d.ts(9,67): error TS2344: Type '"SuperTabButton"' does not satisfy the constraint '"IonIcon" | "IonActionSheetController" | "IonActionSheet" | "IonAlertController" | "IonAlert" | "IonAnchor" | "IonApp" | "IonAvatar" | "IonBackButton" | "IonBackdrop" | "IonBadge" | ... 86 more ... | "IonVirtualScroll"'.
[ng] node_modules/@ionic-super-tabs/angular/dist/directives/proxies.d.ts(15,44): error TS2312: An interface may only extend a class or another interface.
[ng] node_modules/@ionic-super-tabs/angular/dist/directives/proxies.d.ts(15,62): error TS2344: Type '"SuperTabs"' does not satisfy the constraint '"IonIcon" | "IonActionSheetController" | "IonActionSheet" | "IonAlertController" | "IonAlert" | "IonAnchor" | "IonApp" | "IonAvatar" | "IonBackButton" | "IonBackdrop" | "IonBadge" | ... 86 more ... | "IonVirtualScroll"'.
[ng] node_modules/@ionic-super-tabs/angular/dist/directives/proxies.d.ts(22,53): error TS2312: An interface may only extend a class or another interface.
[ng] node_modules/@ionic-super-tabs/angular/dist/directives/proxies.d.ts(22,71): error TS2344: Type '"SuperTabsContainer"' does not satisfy the constraint '"IonIcon"
| "IonActionSheetController" | "IonActionSheet" | "IonAlertController" | "IonAlert" | "IonAnchor" | "IonApp" | "IonAvatar" | "IonBackButton" | "IonBackdrop" | "IonBadge" | ... 86 more ... | "IonVirtualScroll"'.
[ng] node_modules/@ionic-super-tabs/angular/dist/directives/proxies.d.ts(30,51): error TS2312: An interface may only extend a class or another interface.
[ng] node_modules/@ionic-super-tabs/angular/dist/directives/proxies.d.ts(30,69): error TS2344: Type '"SuperTabsToolbar"' does not satisfy the constraint '"IonIcon" |
"IonActionSheetController" | "IonActionSheet" | "IonAlertController" | "IonAlert" | "IonAnchor" | "IonApp" | "IonAvatar" | "IonBackButton" | "IonBackdrop" | "IonBadge" | ... 86 more ... | "IonVirtualScroll"'.
[ng] 
[ng] i ｢wdm｣: Failed to compile.

**Comment by Alkashi** [comment]
Hi @rajkhan91 

Did you manage to solve this pb ?
Thx in advance.

**Comment by Alkashi** [comment]
OK just managed to solve it.

For those who are interested : like its indicated, don't forget to add 
"include": [
    "src",
    "node_modules/@ionic-super-tabs/core/dist/types/interface.d.ts"
  ]
on the tsconfig.json file
