### ISSUE TITLE
Ionic 4 version doesn't work well on device: cannot change active tab

### ISSUE THREAD

**Issue by agrinko** [zyra/ionic-super-tabs#374]
I cloned the latest version of https://github.com/zyra/ionic-super-tabs-example and installed all dependencies. It works fine in the browser. I also updated my own application to the latest version of Ionic Super tabs (v6.0.0-beta.8), and it's also working fine in browser.

Both applications are installed correctly on device, I can see the interface outside of super-tabs, and I can see super tabs toolbar. But changing tabs doesn't work. Tab buttons are clickable, indicator moves left and right, but content is not changed and also I cannot swipe.

This happens on both Android and iOS emulators.

I know Super Tabs for Ionic 4 is still in beta, just wanted to ensure you don't miss this issue. I'd be really thankful for any updates on this. It prevents me from upgrading my app to Ionic 4.

P.S: created a duplicate issue there as well, wasn't sure what's the right place for it
https://github.com/zyra/ionic-super-tabs-example/issues/31

**Comment by st3h3n** [comment]
@agrinko this is the right place as it is clearly an issue with ST not the example implementation.

I can confirm this issue on an actual device (iPhone 6s, Safari, iOS 12.2). Unfortunately this issue doesn't throw an error on the iPhone, so I tried it in an older Android browser and could reproduce the same issue. In the old Android browser it throws this error:
```
TypeError: r.scrollTo is not a function
    at scroll (chunk-39d8d03b.js:1)
    at Array.<anonymous> (chunk-39d8d03b.js:1)
    at p (supertabs.core.js:5)
    at d (supertabs.core.js:5)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17289)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:498)
    at ZoneTask.invoke (zone.js:487)
```
Hope it helps.

**Comment by st3h3n** [comment]
#379 fixed this

**Comment by agrinko** [comment]
@st3h3n , that's great, thank you!
Don't you know when it is going to be released (i.e. tagged beta.9)?

**Comment by st3h3n** [comment]
no, but you can fix it yourself in the meantime:
```
super-tabs-container {
  height: 100%!important;
}
```

**Comment by agrinko** [comment]
Good idea, thank you!
