### ISSUE TITLE
How to disable swipe/drag? 

### ISSUE THREAD

**Issue by ciricc** [zyra/ionic-super-tabs#375]
I need to disable swipe by drag and enable it only by click.
How can I make it?

**Comment by rklus16** [comment]
I think you're looking for the `enableTabsSwipe` method [here](https://github.com/zyra/ionic-super-tabs/tree/v5#enabletabsswipe)

```
ionViewDidLoad() {
  this.superTabs.enableTabsSwipe = false;
}

buttonClick() {
  this.superTabs.enableTabsSwipe = true;
}
```

**Comment by ciricc** [comment]
Thank you
