### ISSUE TITLE
virtualScroll not working

### ISSUE THREAD

**Issue by Shtibel** [zyra/ionic-super-tabs#380]
Hi there,
virtualScroll is not working inside a tab

```
<ion-list [virtualScroll]="albumImagesFilter" [approxItemHeight] ="'300px'">
  <ion-item *virtualItem="let image">
      <ion-img [src]="image.url"></ion-img>
  </ion-item>
</ion-list>
```

How can I make it work?

**Comment by ihadeed** [comment]
Should be working now. Check the example project for reference.

Let me know if you're still having issues.
