### ISSUE TITLE
[6.0.0-beta.10] Usage of ion refresher swipe down issue

### ISSUE THREAD

**Issue by Pingolus** [zyra/ionic-super-tabs#383]
When one tab uses ion refresher ; swipe down on iOS swipes the entire screen ; the tabbar does not stay on the top. 

Seems only appears on iOS ; Android and ionic lab are fine.

Thanks for your work !

**Comment by pipoa** [comment]
Same here,
I think whenever people  swipe left/right, vertical swipe events should be escaped.

**Comment by ihadeed** [comment]
This is due to the bounce effect on iOS that cannot be disabled. Need to figured out what Ionic is doing with their headers and do the same. 

It will definitely improve UX & performance.

**Comment by ihadeed** [comment]
This is fixed by placing super tabs outside of ion-content, then each individual tab can optionally have its own ion-conent if it's not using a nav.

Updated the example project to demonstrate that.
