### ISSUE TITLE
Hello,I want change the position and width of Dom super-tab-indicator

### ISSUE THREAD

**Issue by XiaoQueXinggg** [zyra/ionic-super-tabs#385]
I want change the position and width of Dom super-tab-indicator,it is too long and down .but i am so puzzled ,i hope you can help me.Thanks very much!!!

**Comment by ihadeed** [comment]
@XiaoQueXinggg this function sets the width & position of the indicator: https://github.com/zyra/ionic-super-tabs/blob/master/core/src/super-tabs-toolbar/super-tabs-toolbar.component.tsx#L294
