### ISSUE TITLE
Property 'parent' in type 'SuperTabsComponent' is not assignable to the same property in base type 'NavigationContainer'.

### ISSUE THREAD

**Issue by tamilm47** [zyra/ionic-super-tabs#386]
![save](https://user-images.githubusercontent.com/45138591/64476566-9de3a500-d1ad-11e9-95ce-4ab1f9c58551.PNG)

I got this issue while running ionic s

**Typescript Error**
`Property 'parent' in type 'SuperTabsComponent' is not assignable to the same property in base type 'NavigationContainer'. Type 'NavContro
![save](https://user-images.githubusercontent.com/45138591/64476556-899fa800-d1ad-11e9-95c4-dac6301754b3.PNG)
llerBase' is not assignable to type 'NavController'. Types of property 'config' are incompatible. Type 'import("E:/ionic-try/ionicBlank/node_modules/ionic-angular/umd/config/config").Config' is not assignable to type 'import("E:/ionic-try/ionicBlank/node_modules/ionic-angular/config/config").Config'. Types have separate declarations of a private property '_c'.`

**Comment by ravi-pandit14** [comment]
Please follow this instruction, May be it's help you.
 [click me](https://github.com/zyra/ionic-super-tabs/issues/310#issuecomment-433356892)

**Comment by LucasOta** [comment]
Hi! I also got this problem.
To compile my app for production on Ionic 3 I need Typescript >3+, but SuperTabs brokes as @tamilm47 shows with a version greater than 2.9.x of TS.

Any idea of what can I do to solve this?

**Comment by ravi-pandit14** [comment]
@LucasOta @tamilm47  

> devDependencies should be in package.json:

`"devDependencies": {
    "@ionic/app-scripts": "3.2.2",
    "typescript": "~2.6.2"
`
And this could be resolved this issue.
