### ISSUE TITLE
Hello! I come back again! I have two question. 

### ISSUE THREAD

**Issue by XiaoQueXinggg** [zyra/ionic-super-tabs#389]
One,when i produce app in computer，all pages translate very good . However, i package it to phone ,that pages translate badly and it is no easy and smooth ,
Two ,sometime, i click the superb-utton, relatived page not swipe and no action， and it is no wrong in PC，only in phone.
please ignore my grammar，it is no good.
expecting  your reply !!!

**Comment by ihadeed** [comment]
Hey @XiaoQueXinggg

Can you describe the behavior your experiencing on mobile with more details?

**Comment by XiaoQueXinggg** [comment]
i slide my phone down , it flip to automatically and container stay for between container and close contanier   somtimes  i click tab it can't flip and no reaction, i don't know i can descibe it or not.

**Comment by garyc2232** [comment]
Hi, I have the same experiences on that.
My situation is when i tap a super-tab-button, the content inside super-tab did not change but the button and the button indicator did activated. 
I have tried many times, it always fail on my iPhone XR and safari browser and sometimes fail on my Android (Samsung C5) and chrome browser.

But when i tested MacBook chrome and safari, there are no such issue.

Please help thanks.

**Comment by ihadeed** [comment]
@garyc2232 Can you try 6.1.3-alpha.1 ?

**Comment by ihadeed** [comment]
@XiaoQueXinggg @garyc2232 
Can you try `6.1.3-alpha.1` ?

**Comment by garyc2232** [comment]
It works, thanks a lot.
