### ISSUE TITLE
Minor fixes for fixed tabs Material specs

### ISSUE THREAD

**Issue by plusCubed** [zyra/ionic-super-tabs#39]
These are a few of the defaults that I found were slightly off (for fixed tabs) from the [spec](https://material.io/guidelines/components/tabs.html#tabs-specs). I think it would be best if some of these attributes are user-configurable. 

- Height: 48px
- Padding on left/right of text: 12px
- Larger screens (desktop in the guidelines): 
  - Centered/left-aligned to side menu button
  - Text size: 13px
  - Padding on left/right of text: 24px

Thank you for your efforts! These minor design fixes would make the library even better.

**Comment by ihadeed** [comment]
I've implemented the correct dimensions for the mobile view. I will add the desktop dimensions in the next release. I will also add add an option to align the scrollable tabs with the keyline, as demonstrated in the specs:

![image](https://cloud.githubusercontent.com/assets/13794420/26243233/2215dec0-3c59-11e7-80ef-09431f9afba1.png)

**Comment by ITServicesAM** [comment]
How is it going so far? Any progress here for desktop?
