### ISSUE TITLE
Toolbar Indicator color

### ISSUE THREAD

**Issue by malua** [zyra/ionic-super-tabs#393]
Hey!

Thanks for this awesome tabs component!
I have a rather simple question, but I can't find the answer anywhere.

I would like to change the color of the toolbar indicator. I tried with css vars and looked through the type definitions, but I can't figure it out.

Thanks in advance!

**Comment by ihadeed** [comment]
Hi @malua

You can set the CSS variable that can be found in the generated docs here:

https://github.com/zyra/ionic-super-tabs/blob/master/core/src/super-tab-indicator/readme.md

**Comment by ihadeed** [comment]
Also if you set the color property for the toolbar component (docs: https://github.com/zyra/ionic-super-tabs/blob/master/core/src/super-tabs-toolbar/readme.md) it should automatically pick up the contrast color defined in your ionic `variables.scss`

**Comment by malua** [comment]
Thank you!
