### ISSUE TITLE
Bug: SuperTabs.selectTab does not trigger (activeTabIndexChange)

### ISSUE THREAD

**Issue by malua** [zyra/ionic-super-tabs#394]
Hey,

maybe i am doing it wrong but when i use
`superTabs.selectTab(index)` it changes the tab but neither `(activeTabIndexChange)` nor `(tabChange)` emit anything.

I am using Angular 8 and get the SuperTabs Ref with ViewChild:
` @ViewChild(SuperTabs, { static: false }) superTabs: SuperTabs;`

Thanks for your help (again)!
All the best

**Comment by pbnsilva** [comment]
This problem persists in the latest version. `activeTabIndex` is unchanged after `selectTab`.
