### ISSUE TITLE
how beginner to start

### ISSUE THREAD

**Issue by zsq2010** [zyra/ionic-super-tabs#395]
I just come with, 
angular8/ionic4/npm i -S @ionic-super-tabs/angula

hopeful to start with some guide or video to run this project
===================
I've followed instruction,but get a plain-text to display,seems lack of css or sth

can someone.shows some basic to start ,complete guid is needed for people like me at low level: (
--------------------------------
<<A quick getting started guide:>>

# Angular
npm i -S @ionic-super-tabs/angular

# Non angular
npm i -S @ionic-super-tabs/core

// Angular only

// App.module.ts
import { SuperTabsModule } from '@ionic-super-tabs/angular'

@NgModule({ 
 ... 
  imports: [
    ...
    SuperTabsModule.forRoot(),
  ]
})

// your lazy loaded module
@NgModule({
   ...
   imports: [
     ...,
     SuperTabsModule,
   ]
})

<super-tabs>
  <super-tabs-toolbar position="top">
    <super-tab-button>
       <ion-icon name="flame">
       <ion-label>Hello</ion-label>
    </super-tab-button>
    <super-tab-button>
       <ion-icon name="call">
       <ion-label>World</ion-label>
    </super-tab-button>
  </super-tabs-toolbar>
  <super-tabs-container>
    <super-tab>
       Im a custom page
    </super-tab>
    <super-tab>
       <ion-nav root="some page" />
    </super-tab>
  <super-tabs-container>
</super-tabs>
----

**Comment by ihadeed** [comment]
Example repo is a good place to start https://github.com/zyra/ionic-super-tabs-example
WIP docs can be found here: https://zyra.github.io/ionic-super-tabs/
