### ISSUE TITLE
Not able to scroll content present inside tab vertically

### ISSUE THREAD

**Issue by playstorehightech** [zyra/ionic-super-tabs#397]
This is my simle HTML,
Also tab position at top is not working.

 
![image](https://user-images.githubusercontent.com/56752460/68544687-cb3a1280-03eb-11ea-8dcf-b2f66e7669d5.png)

**Comment by ihadeed** [comment]
What version of super tabs are you using?

**Comment by playstorehightech** [comment]
"@ionic-super-tabs/angular": "^6.0.0-rc.5",

**Comment by ihadeed** [comment]
@playstorehightech can you try `6.0.3`? 

```
npm i -S @ionic-super-tabs/{core,angular}@latest
```

**Comment by ihadeed** [comment]
You need to place the content inside `<ion-content>`. 

Quick example:
```html
<ion-header>
  <!-- ... -->
</ion-header>
<super-tabs>
  <super-tabs-content>
    <super-tab>
       <ion-content>
            <!-- your content here -->
       </ion-content>
    </super-tab>
  </super-tabs-content>
  <!-- other tabs -->
</super-tabs>
```

**Comment by playstorehightech** [comment]
Thanks 
Its working fine now with latest version

**Comment by playstorehightech** [comment]
@ihadeed 
Can you tell me how to apply horizontal scroll for tab names?
I am having 5 tabs and that can not fit into screen(see image uploaded), so I need horizontal scroll for tab names
![image](https://user-images.githubusercontent.com/56752460/69010049-63eb0800-0981-11ea-8d30-a726d251f104.png)


My code:
![image](https://user-images.githubusercontent.com/56752460/69010086-b75d5600-0981-11ea-9af2-8927dbe5e2d8.png)
