### ISSUE TITLE
selectTab no longer updates active tab indicator

### ISSUE THREAD

**Issue by st3h3n** [zyra/ionic-super-tabs#399]
When calling `SuperTabs.selectTab()` the active tab indicator doesn't update. This is due to the now required flag `align` on `SuperTabsToolbar.setActiveTab()` introduced in 045ca2f. That flag is not set by `selectTab()`.

**Expected behavior**
`selectTab()` should set `align` to `true` to reflect previous behavior. If that is undesired it should at least offer the option by providing this functionality through an `align` flag on `selectTab()`.

Also: the `animate` flag is not forwarded to `SuperTabsToolbar.setActiveTab()`, which it probably should and since 045ca2f the flag is even completely ignored.

**Comment by ihadeed** [comment]
Thanks @st3h3n 

I really appreciate the detailed bug report!

Just pushed a fix and published `6.1.1`
