### ISSUE TITLE
Swipe super tab does not work on iOS, whenever I change it changes only tabs, but stays with old page content

### ISSUE THREAD

**Issue by JuniorFlorentino** [zyra/ionic-super-tabs#401]
<super-tabs [config]="config" (tabChange)="onTabChange($event)">
    <super-tabs-toolbar class="barra_up" [scrollable]="true" scrollablePadding="false"> 
        <super-tab-button>
                <ion-img class="icon_situacao_atual" src="../../assets/img/boletos/icon_aberto2.png"></ion-img>
            <ion-label class="titulo_status">Aberto</ion-label>
        </super-tab-button>
        <super-tab-button>
                <ion-img class="icon_situacao_atual" src="../../assets/img/boletos/bar_red_vencido2.png"></ion-img>
            <ion-label class="titulo_status">Vencido</ion-label>
        </super-tab-button>
        <super-tab-button>
                <ion-img class="icon_situacao_atual" src="../../assets/img/boletos/icon_baixado2.png"></ion-img>
            <ion-label class="titulo_status">Baixado</ion-label>
        </super-tab-button>

        <super-tab-button>
                <ion-img class="icon_situacao_atual" src="../../assets/img/boletos/icon_negociado2.png"></ion-img>
            <ion-label class="titulo_status">Negociado</ion-label>
        </super-tab-button>
    </super-tabs-toolbar>

    <super-tabs-container>
        <super-tab>
            <ion-content>
            <ion-card *ngFor="let item of aberto; let i = index">

                <table class="tabela" border="0" *ngIf="aberto.length > 0">
                    <tr>
                        <td rowspan="3" class="img-col col-sm-1 col-xs-1 col-md-1 col-lg-1"
                            (click)="abrirBoletoDetalhe(item)">
                            <ion-item style="--border-style: none;">
                                <ion-avatar item-start>
                                    <ion-icon class="icon_situacao" name="barcode" *ngIf="item.situacao=='ABERTO'">
                                    </ion-icon>

                                    <ion-icon class="icon_situacao" name="barcode" *ngIf="item.situacao=='VENCIDO'">
                                    </ion-icon>

                                    <ion-icon class="icon_situacao" name="barcode" *ngIf="item.situacao=='BAIXADO'">
                                    </ion-icon>

                                    <ion-icon class="icon_situacao" name="barcode"
                                        *ngIf="item.situacao=='NEGOCIADO'"></ion-icon>

                                    <ion-icon name="md-cash" item-left class="icon-bloqueado icon-large"
                                        *ngIf="item.situacao=='BLOQUEADO'">
                                    </ion-icon>
                                </ion-avatar>
                            </ion-item>
                        </td>
                        <td class="vencimento" (click)="abrirBoletoDetalhe(item)">
                            {{item.cre_data_vencimento}}
                        </td>
                        <td>

                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td (click)="abrirBoletoDetalhe(item)">
                            <strong class="referencia">
                                Ref.: {{item.ref_referencia}}
                            </strong>
                        </td>
                        <td (click)="abrirBoletoDetalhe(item)">
                            <div class="valor">R$ {{item.cre_valor}} </div>
                        </td>
                        <td>

                            <div class="icon_detalhes" (click)="abrirBoletoDetalhe(item)">
                                <ion-icon size="large" name="ios-more"></ion-icon>
                            </div>

                        </td>
                    </tr>

                </table>

            </ion-card>
            <div class="nao_existe" *ngIf="aberto.length < 1 && exibirMsg==true">
                Não existe boleto Aberto
            </div>
        </ion-content>
        </super-tab>
        <super-tab>
            <ion-content>
            <ion-card *ngFor="let item of vencido; let i = index">

                <table class="tabela" border="0">
                    <tr>
                        <td rowspan="3" class="img-col col-sm-1 col-xs-1 col-md-1 col-lg-1"
                            (click)="abrirBoletoDetalhe(item)">
                            <ion-item style="--border-style: none;">
                                <ion-avatar item-start>
                                    <ion-icon class="icon_situacao" name="barcode" *ngIf="item.situacao=='ABERTO'">
                                    </ion-icon>

                                    <ion-icon class="icon_situacao" name="barcode" *ngIf="item.situacao=='VENCIDO'">
                                    </ion-icon>

                                    <ion-icon class="icon_situacao" name="barcode" *ngIf="item.situacao=='BAIXADO'">
                                    </ion-icon>

                                    <ion-icon class="icon_situacao" name="barcode"
                                        *ngIf="item.situacao=='NEGOCIADO'"></ion-icon>

                                    <ion-icon name="md-cash" item-left class="icon-bloqueado icon-large"
                                        *ngIf="item.situacao=='BLOQUEADO'">
                                    </ion-icon>
                                </ion-avatar>
                            </ion-item>
                        </td>
                        <td class="vencimento" (click)="abrirBoletoDetalhe(item)">
                            {{item.cre_data_vencimento}}
                        </td>
                        <td>

                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td (click)="abrirBoletoDetalhe(item)">
                            <strong class="referencia">
                                Ref.: {{item.ref_referencia}}
                            </strong>
                        </td>
                        <td (click)="abrirBoletoDetalhe(item)">
                            <div class="valor">R$ {{item.cre_valor}} </div>
                        </td>
                        <td>

                            <div class="icon_detalhes" (click)="abrirBoletoDetalhe(item)">
                                <ion-icon size="large" name="ios-more"></ion-icon>
                            </div>

                        </td>
                    </tr>

                </table>

            </ion-card>
            <div class="nao_existe" *ngIf="vencido.length < 1 && exibirMsg==true">
                Não existe boleto Vencido
            </div>
        </ion-content>
        </super-tab>
        <super-tab>
            <ion-content>
            <ion-card *ngFor="let item of baixado; let i = index">

                <table class="tabela" border="0" *ngIf="baixado.length > 0">
                    <tr>
                        <td rowspan="3" class="img-col col-sm-1 col-xs-1 col-md-1 col-lg-1"
                            (click)="abrirBoletoDetalhe(item)">
                            <ion-item style="--border-style: none;">
                                <ion-avatar item-start>
                                    <ion-icon class="icon_situacao" name="barcode" *ngIf="item.situacao=='ABERTO'">
                                    </ion-icon>

                                    <ion-icon class="icon_situacao" name="barcode" *ngIf="item.situacao=='VENCIDO'">
                                    </ion-icon>

                                    <ion-icon class="icon_situacao" name="barcode" *ngIf="item.situacao=='BAIXADO'">
                                    </ion-icon>

                                    <ion-icon class="icon_situacao" name="barcode"
                                        *ngIf="item.situacao=='NEGOCIADO'"></ion-icon>

                                    <ion-icon name="md-cash" item-left class="icon-bloqueado icon-large"
                                        *ngIf="item.situacao=='BLOQUEADO'">
                                    </ion-icon>
                                </ion-avatar>
                            </ion-item>
                        </td>
                        <td class="vencimento" (click)="abrirBoletoDetalhe(item)">
                            {{item.cre_data_vencimento}}
                        </td>
                        <td>

                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td (click)="abrirBoletoDetalhe(item)">
                            <strong class="referencia">
                                Ref.: {{item.ref_referencia}}
                            </strong>
                        </td>
                        <td (click)="abrirBoletoDetalhe(item)">
                            <div class="valor">R$ {{item.cre_valor}} </div>
                        </td>
                        <td>

                            <div class="icon_detalhes" (click)="abrirBoletoDetalhe(item)">
                                <ion-icon size="large" name="ios-more"></ion-icon>
                            </div>

                        </td>
                    </tr>

                </table>

            </ion-card>
            <div class="nao_existe" *ngIf="baixado.length < 1 && exibirMsg==true">
                Não existe boleto Baixado
            </div>
        </ion-content>
        </super-tab>

        <super-tab>
            <ion-content>
            <ion-card *ngFor="let item of negociado; let i = index">

                <table class="tabela" border="0" *ngIf="negociado.length > 0">
                    <tr>
                        <td rowspan="3" class="img-col col-sm-1 col-xs-1 col-md-1 col-lg-1"
                            (click)="abrirBoletoDetalhe(item)">
                            <ion-item style="--border-style: none;">
                                <ion-avatar item-start>
                                    <ion-icon class="icon_situacao" name="barcode" *ngIf="item.situacao=='ABERTO'">
                                    </ion-icon>

                                    <ion-icon class="icon_situacao" name="barcode" *ngIf="item.situacao=='VENCIDO'">
                                    </ion-icon>

                                    <ion-icon class="icon_situacao" name="barcode" *ngIf="item.situacao=='BAIXADO'">
                                    </ion-icon>

                                    <ion-icon class="icon_situacao" name="barcode"
                                        *ngIf="item.situacao=='NEGOCIADO'"></ion-icon>

                                    <ion-icon name="md-cash" item-left class="icon-bloqueado icon-large"
                                        *ngIf="item.situacao=='BLOQUEADO'">
                                    </ion-icon>
                                </ion-avatar>
                            </ion-item>
                        </td>
                        <td class="vencimento" (click)="abrirBoletoDetalhe(item)">
                            {{item.cre_data_vencimento}}
                        </td>
                        <td>

                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td (click)="abrirBoletoDetalhe(item)">
                            <strong class="referencia">
                                Ref.: {{item.ref_referencia}}
                            </strong>
                        </td>
                        <td (click)="abrirBoletoDetalhe(item)">
                            <div class="valor">R$ {{item.cre_valor}} </div>
                        </td>
                        <td>

                            <div class="icon_detalhes" (click)="abrirBoletoDetalhe(item)">
                                <ion-icon size="large" name="ios-more"></ion-icon>
                            </div>

                        </td>
                    </tr>

                </table>

            </ion-card>
            <div class="nao_existe" *ngIf="negociado.length < 1 && exibirMsg==true">
                Não existe boleto Negociado
            </div>
        </ion-content>
        </super-tab>
    </super-tabs-container>
</super-tabs>
![69152787-d95af380-0abb-11ea-8b51-598fead3f471](https://user-images.githubusercontent.com/17836169/69424348-24b51200-0d07-11ea-89cb-b66d8e27d905.gif)

**Comment by ihadeed** [comment]
@JuniorFlorentino  Can you try `6.1.3-alpha.1` ?

**Comment by JuniorFlorentino** [comment]
can, yes

**Comment by Gamaroff** [comment]
This issue is still happening on iOS with 

```
"@ionic-super-tabs/angular": "^6.1.3-alpha.1"
"@ionic-super-tabs/core": "^6.1.3-alpha.1"
```

**Comment by ihadeed** [comment]
Try the latest `6.2.0` version.
