### ISSUE TITLE
Can not change tab index pragmatically (in page.ts file)

### ISSUE THREAD

**Issue by playstorehightech** [zyra/ionic-super-tabs#403]
Can you guys please let me know how to change tab index in page.ts file?

**Comment by AlejandroMuralles** [comment]
Get the supertabs with the decorator
@ViewChild('superTabs', { static: false, read: SuperTabs }) st: SuperTabs;

Then just
this.st.selectTab(index);

Works fine in the browser even when I test it on real device (Android) but when I make the production release... just stop working

**Comment by tebantebanteban** [comment]
Same here @AlejandroMuralles

**Comment by ihadeed** [comment]
Try with latest version `6.2.0`
