### ISSUE TITLE
Error when use ion-input into super-tab: current tab content disappears

### ISSUE THREAD

**Issue by marcovgiunta** [zyra/ionic-super-tabs#406]
When i put an ion-input into super-tab different from first super-tab in list, i get the current tab content disappears while first tab content appears when keyboard opens.

1. Clone ionic-super-tabs-example and than npm update super-tabs to last version
2. Put this into 2° tab "contacts":

           `<ion-item>
              <ion-label position="fixed">input 1</ion-label>
              <ion-input></ion-input>
            </ion-item>
            <ion-item>
              <ion-label position="fixed">input 2</ion-label>
              <ion-input></ion-input>
            </ion-item> 
            <ion-item>
              <ion-label position="fixed">input 3</ion-label>
              <ion-input></ion-input>
            </ion-item>
            <ion-item>
              <ion-label position="fixed">input 4</ion-label>
              <ion-input></ion-input>
            </ion-item>
            <ion-item>
              <ion-label position="fixed">input 5</ion-label>
              <ion-input></ion-input>
            </ion-item>
            <ion-item>
              <ion-label position="fixed">input 6</ion-label>
              <ion-input></ion-input>
            </ion-item>
            <ion-item>
              <ion-label position="fixed">input 7</ion-label>
              <ion-input></ion-input>
            </ion-item>`

3. Tap or click on one of inputs in list 
4. On IOS you will see current content disappear while content of tab #1 will appear when keyboard comes up, and then return normal
    On browser you will see current content disappear while content of tab #1 will appear fixed

Update: replacing ion-input with normal html input tags it seems to work, but i lost all ion-input binded functions

**Comment by marcovgiunta** [comment]
Update 2: if you turn off scrollAssist bug disappears:

`IonicModule.forRoot({ 
      scrollPadding: false,
      scrollAssist: false 
    }),`

But it's necessary to manual implement a scroll assist when input get focus

**Comment by ihadeed** [comment]
Thanks for reporting this.

It's possibly due to Ionic expecting to find a single active `ion-content` at a time and it doesn't recognize the real active tab.

**Comment by ihadeed** [comment]
Try the latest `6.2.0` version.

**Comment by danbn-100295** [comment]
Have same issue,how can i fix it ??
