### ISSUE TITLE
CDN version gives error "module is not defined"

### ISSUE THREAD

**Issue by Tommertom** [zyra/ionic-super-tabs#408]
**Describe the bug**

I tried to included supertabs as CDN via script tag:
```
  <script
    src="https://cdn.jsdelivr.net/npm/@ionic-super-tabs/core@6.1.3-alpha.1/dist/index.min.js">
  </script>
```
Gives error at load time:
```
Uncaught ReferenceError: module is not defined
at index.min.js:5
(anonymous) | @ | index.min.js:5
```
A local compiled version (local dist folder reference) gives same error.

**To Reproduce**
See above. Add the package via CDN.

**Expected behavior**
No error and webcomponents available.

**Screenshots**
n/a

**Desktop (please complete the following information):**
Win10 desktop, Chrome 78

**Smartphone (please complete the following information):**
 n/a

**Additional context**
Integrated as part of svelte integration try-out through the webcomponent feature of stenciljs

**Comment by ihadeed** [comment]
I don't think that file exists.

Try importing `https://cdn.jsdelivr.net/npm/@ionic-super-tabs/core@6.1.3-alpha.1/dist/supertabs.js` instead.
