### ISSUE TITLE
I can't use *ngFor on super-tab-button

### ISSUE THREAD

**Issue by AminTakmili** [zyra/ionic-super-tabs#410]
I can't use ***ngFor** on `super-tab-button`

Here is the code I'm using:

```html
<super-tabs *ngIf="tabsLoaded" class="ion-hide-lg-up" activeTabIndex="2"
	[config]="{ debug: false, sideMenu: 'left', allowElementScroll: true }">
	<super-tabs-toolbar slot="top">
		<super-tab-button *ngFor="item of categories | reverse">
			<ion-label>{{ item.name }}</ion-label>
		</super-tab-button>
		
	</super-tabs-toolbar>

	<super-tabs-container>
		<super-tab *ngFor="item of categories | reverse">
			<ion-content class="ion-padding">
				{{ item.id }}
			</ion-content>
		</super-tab>
	</super-tabs-container>
</super-tabs>
```

It throws this error:
**Can't bind to 'ngFor' since it isn't a known property of 'super-tab-button'.**

**Comment by VaultDeveloper** [comment]
Your tag is `super-tab-button` instead of `super-**f**ab-button`.

**Comment by ihadeed** [comment]
The scrollable example uses ngFor: https://github.com/zyra/ionic-super-tabs-example/blob/master/src/app/%2Bpages/scrollable/scrollable.page.html

Compare it to your code and try to eliminate any differences until you find the cause.

If it's a bug with the module let me know and I'll look into it.
