### ISSUE TITLE
Why use ion-content ?

### ISSUE THREAD

**Issue by VaultDeveloper** [zyra/ionic-super-tabs#412]
I understand that we need to use `ion-content` for each `super-tab` to be able to swipe under the `super-tab`.

Why this choice ? Why don't use a `ion-slides` from Ionic ?

How can we integrate `ionic-super-tabs` under a component that is already under `ion-content` ?

Is it possible to have nested `ionic-super-tabs` ?

**Comment by ihadeed** [comment]
> I understand that we need to use ion-content for each super-tab to be able to swipe under the super-tab.

As of now yes, it's not required to use that component/tag specifically, but it already has some CSS properties and possible side effects that allow it to scroll properly on mobile. I didn't have the time to look into that so for the time being I suggest using it.

> Why this choice ? Why don't use a ion-slides from Ionic ?

This module was initially built on top of ion-slides. Moved to a custom integration for better performance.

> How can we integrate ionic-super-tabs under a component that is already under ion-content ?

Currently there isn't a solution. You probably don't need an `ion-content` in the root component if you use a fixed layout.

> Is it possible to have nested ionic-super-tabs ?

It's not a priority and it's never tested. Nested components that swipe in the same direction isn't a good UX/UI practice. Not worth putting efforts into making it work.

**Comment by ihadeed** [comment]
`v6.2.0` doesn't require `ion-content` anymore
