### ISSUE TITLE
event TabChange not emitted

### ISSUE THREAD

**Issue by ArieVanWalraven** [zyra/ionic-super-tabs#414]
When I try to handle event tabChange using the following code:

`<super-tabs (tabChange)="onTabChange($event)">`

my IDE (WebStorm) gives the error message "Event tabChange is not emitted by any applicable directives nor by super-tabs element ". I'm using @ionic-super-tabs/angular": "^6.1.3-alpha.1" and Ionic Framework @ionic/angular 4.11.7.

The same applies to events 'activeTabIndexChange' and 'selectedTabIndexChange' in 'super-tabs-container'.

**Comment by tebantebanteban** [comment]
solved replacing

`this.setupEventListeners();`
for

```
setTimeout(async () => { // XXX
                this.setupEventListeners();
            }, 1000);
```

in node_modules/@ionic-super-tabs/core/dist/esm/super-tab_3.entry.js
