### ISSUE TITLE
selectTab does not exist  on type SuperTabs

### ISSUE THREAD

**Issue by tebantebanteban** [zyra/ionic-super-tabs#416]
selectTab works in development, but in build not work

**Comment by RobinGiel** [comment]
I'm trying to find a solution for this problem, in the meanwhile did you fing any work around? @tebantebanteban

**Comment by tebantebanteban** [comment]
> I'm trying to find a solution for this problem, in the meanwhile did you fing any work around? @tebantebanteban

Yes, is not clean but works perfect and solve problem

I make a function 

```
goToTab(index){
       setTimeout(function(){
            let element: HTMLElement = document.getElementById('tab'+index) as HTMLElement;
            element.click()
       }, 10);
   }
```

and assign an id for all super-tab-button for example. id="tab0", id="tab1", id="tab2"

And call function with

this.goToTab(1)

**Comment by RobinGiel** [comment]
[https://github.com/zyra/ionic-super-tabs/issues/417#issuecomment-581451576](url)

this worked for me @tebantebanteban
