### ISSUE TITLE
Side menu swipe and activeTabIndex are not working in production/release mode

### ISSUE THREAD

**Issue by csivaram** [zyra/ionic-super-tabs#417]
<super-tabs [activeTabIndex]="tabId" (tabChange)="onTabChange($event)" [config]="config">

config: SuperTabsConfig = {
    sideMenu: 'both',
    allowElementScroll: true
}

ngOnInit() {
    this.tabId = "2";
}

My app has side menu on both sides. It is perfectly working in debug mode when i build and run using: "ionic cordova run android". 

But when i build and run for production mode using "ionic cordova run android --prod --release", 
1. the side menu swipe is not working and 
2. always the first tab is selected in spite of setting "this.tabId" to "2".

**Comment by RobinGiel** [comment]
This is happening only on android, on iOs I have no problem so far. Hope to find a fix soon or a work around

**Comment by RobinGiel** [comment]
This has somthing to do with the --prod build. Maybe hashing or optimizing the project and by doing this not reaching the stencil component correctly. I was trying to debug this but no solution so far. I see 3 similar issues already

**Comment by pszalanski** [comment]
We have issues in a `--prod` build as well. Reacting to tab switching and swiping subcomponents marked with `avoid-super-tabs` do not work in production.

**Comment by RobinGiel** [comment]
@pszalanski Thanks for the tip! setting buildOptimizer to false worked for me. I see an increase of 1mb after doing this, but it's a work around for the moment, hopefully someone can solve this or the author can take a look at it :-)
