### ISSUE TITLE
Cannot read property 'getRootScrollableEl' of undefined

### ISSUE THREAD

**Issue by kartubai** [zyra/ionic-super-tabs#418]
I am facing this issue while opening my super tabs page for the second time
Cannot read property 'getRootScrollableEl' of undefined. Can anyone please help me on this?

![image](https://user-images.githubusercontent.com/60942658/74273225-15f26000-4d36-11ea-955e-266074d6a6e6.png)

**Comment by ihadeed** [comment]
Try with latest version `6.2.0`
