### ISSUE TITLE
How can i listen to each time tab has selected?

### ISSUE THREAD

**Issue by elkhalifte** [zyra/ionic-super-tabs#420]
Is there any way I can listen to the active tab so I can do something .

Thank you .

**Comment by elkhalifte** [comment]
I Found the solution

**Comment by indrapalijama** [comment]
> I Found the solution

hi!, can you explain to me how'd you do that? Thanks

**Comment by elkhalifte** [comment]
i used ionChange event
 <super-tabs activeTabIndex="2" (tabChange)="callme($event)">


`  callme(ev: CustomEvent<SuperTabChangeEventDetail>){
    switch (ev.detail.index){
      case 0:
        if(this.currenttab == 2){console.log('Tab 2 Leaved')}
        if(this.currenttab == 1){console.log('Tab 1 Leaved')}
        console.log('Tab 0 Entered')
        this.currenttab = 0;
       break;
      case 1:
        if(this.currenttab == 2){console.log('Tab 2 Leaved')}
        if(this.currenttab == 0){console.log('Tab 0 Leaved')}
        console.log('Tab 1 Entered')
        this.currenttab = 1;
       break;
      case 2:
        if(this.currenttab == 0){console.log('Tab 0 Leaved')}
        if(this.currenttab == 1){console.log('Tab 1 Leaved')}
        console.log('Tab 2 Entered')
        this.currenttab = 2;
       break;
    }`

Hope this will help!

**Comment by indrapalijama** [comment]
> i used ionChange event
> <super-tabs activeTabIndex="2" (tabChange)="callme($event)">
> 
> ```
> import { SuperTabs } from '@ionic-super-tabs/angular'; 
> import { SuperTabChangeEventDetail } from '@ionic-super-tabs/core';
> 
> callme(ev: CustomEvent<SuperTabChangeEventDetail>){
> 
>     switch (ev.detail.index){
>       case 0:
> 
>         if(this.currenttab == 2){console.log('Tab 2 Leaved')}
> 
>         if(this.currenttab == 1){console.log('Tab 1 Leaved')}
> 
>         console.log('Tab 0 Entered')
> 
>         this.currenttab = 0;
> 
>        break;
> 
>       case 1:
> 
>         if(this.currenttab == 2){console.log('Tab 2 Leaved')}
> 
>         if(this.currenttab == 0){console.log('Tab 0 Leaved')}
> 
>         console.log('Tab 1 Entered')
> 
>         this.currenttab = 1;
> 
>        break;
> 
>       case 2:
> 
>         if(this.currenttab == 0){console.log('Tab 0 Leaved')}
> 
>         if(this.currenttab == 1){console.log('Tab 1 Leaved')}
> 
>         console.log('Tab 2 Entered')
> 
>         this.currenttab = 2;
> 
>        break;
> 
>     }
> ```
> 
> Hope this will help!

Thanks!
