### ISSUE TITLE
Tabs shown after initialization are not considered for width calculation and swipe

### ISSUE THREAD

**Issue by rastafan** [zyra/ionic-super-tabs#422]
Hi,

we have supertabs in our app. 
Content has 5 tabs, but at initialization only two are shown. Then 4 more are shown later, based on data received from server.
This leads to a wrong computed size in `indexTabs`, and tabs won't swipe beyond index 1 since `tabsWidth` in `calcSelectedTab` is just 2 tabs wide (even tho there are 4 shown now).

Is there any way to refresh `tabsWidth` value? Something like calling `indexTabs` programmatically?

Thanks a lot.

**Comment by ihadeed** [comment]
Fixed by https://github.com/zyra/ionic-super-tabs/commit/31fb1a4ebcd61261e41ceed861ce95d9e54d5d8e
