### ISSUE TITLE
super-tab  get the data *ngFor is not working 

### ISSUE THREAD

**Issue by rahul635** [zyra/ionic-super-tabs#424]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rahul635** [comment]
"ionic2-super-tabs": "^4.1.4",

**Comment by rahul635** [comment]
Hey, is any solution available for it?

**Comment by ihadeed** [comment]
Old version doesn't support dynamic ngFor. Data must be loaded and defined before rendering. 

Need to wrap the whole super tabs component with an ngIf to make sure that it only renders when your data is available.
