### ISSUE TITLE
Tabs background color doesn't change on light/dark theme switch.

### ISSUE THREAD

**Issue by tiagossa1** [zyra/ionic-super-tabs#429]
**Describe the bug**
Tabs background color or tab label color doesn't change on light/dark theme switch.
This bug only applies for Android, on desktop browser is working fine.

**To Reproduce**
Put this code on the module .scss:

```
:root {
  --st-indicator-color: #3880ff;
  --st-base-color-active: #3880ff;
}

@media (prefers-color-scheme: light) {
  :root {
    --super-tabs-toolbar-background: white;
    --st-base-color-inactive: black;
  }
}

@media (prefers-color-scheme: dark) {
  :root {
    --super-tabs-toolbar-background: #121212;
    --st-base-color-inactive: white;
  }
}
```

**Expected behavior**
If the dark theme is activated, the tab background should be dark and on light theme, it should be white.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80.0.3987.163

**Smartphone (please complete the following information):**
 - Device: Mi 9T/Redmi K20
 - OS: Android 10

**Comment by ihadeed** [comment]
Tested your example and it works for me. Versions prior to `6.1.0` had issues with CSS variables so make sure you're using at least `6.1.0`. 

Also if that css code isn't in `variables.scss` you need to use `:host` instead of `:root`.
