### ISSUE TITLE
ionic 4 lazy load

### ISSUE THREAD

**Issue by indrapalijama** [zyra/ionic-super-tabs#431]
hi! is there a way to implement lazy load feature in ionic 4? i'd already tried but all of my tab component got load

**Comment by davidquon** [comment]
I've been looking for the same answer.  🙏

**Comment by masterbd** [comment]
The author mentioned in documentation that lazy loading is not supported yet. 
https://zyra.github.io/ionic-super-tabs/usage/angular.

Therefore I don't think is going to be a huge problem, as this packaged is more suitable for mobile apps (not PWA) where all files are locally and loading them all should not cause a considerable difference in performance.
