### ISSUE TITLE
Support for Ionic 5 ?

### ISSUE THREAD

**Issue by aditbharadwaj** [zyra/ionic-super-tabs#433]
Does the super tabs work in ionic 5?  and if not can we have separate branch for this as well as like ionic 4 and ionic 3 ty

**Comment by masterbd** [comment]
I have added it recently in a new Ionic 5 app and works for me. What problem do you have?

**Comment by aditbharadwaj** [comment]
> I have added it recently in a new Ionic 5 app and works for me. What problem do you have?

not any problem i was wondering if it works or not or will it cause some problems if i use it

**Comment by masterbd** [comment]
For me it is working perfectly. 
The only one missing thing is that lazy loading is not yet supported, but this is not a huge decision factor for me, as I'm building just mobile apps not PWA. In mobile all files are locally and I don't need as much lazy loading.

**Comment by ihadeed** [comment]
Previous versions should work. Latest 7.0.0 release is built with latest Ionic/Angular.
