### ISSUE TITLE
Bottom Shadow Remove

### ISSUE THREAD

**Issue by breakdom** [zyra/ionic-super-tabs#435]
Hi, I want remove material design shadow under the bottom of "super-tabs-toolbar".

I'm trying to create a toolbar with a transparent background and no border to make it float above the slide.
After this I will also have to change the general width of the bar.

For the moment I can not remove that shadow below, I also tried to look in the component but I did not find reference to box-shadow

**Comment by masterbd** [comment]
Look into :after pseudo-element  for super-tabs-container. I was able to remove it using this:

```
super-tabs-toolbar {
  &:after {
    background: transparent;
  }
}
```

That shadow, if we speak about same things, is not built using box-shadow, instead it is a base64 added as background-image to the toolbar.

**Comment by breakdom** [comment]
Sorry I forgot to publish this request, I checked it works! Big thanks.

**Comment by ihadeed** [comment]
You can add `no-border` attribute and that will remove it. Similar to how `<ion-header>` works.

```html
<super-tabs-toolbar no-border>
  ...
</super-tabs>
```
