### ISSUE TITLE
how to set default tab in super tab

### ISSUE THREAD

**Issue by bala-arun-s** [zyra/ionic-super-tabs#442]
I don't how to set default tab to show when I am loading a page 
and how to navigate to specific tab from outside of super tab

if you have any solution for this problem kindly replay

**Comment by ihadeed** [comment]
https://zyra.github.io/ionic-super-tabs/components/super-tabs/

`activeTabIndex` property allows to you set the initial tab ([Example](https://github.com/zyra/ionic-super-tabs-example/blob/master/src/app/%2Bpages/full-screen/full-screen.page.html#L4))

```ts
selectTab(index: number, animate?: boolean, emit?: boolean) => Promise<void>
```
`selectTab` method is for manually switching tabs. ([Example](https://github.com/zyra/ionic-super-tabs-example/blob/master/src/app/%2Bpages/full-screen/full-screen.page.ts))

**Comment by bala-arun-s** [comment]
thanks man
