### ISSUE TITLE
nested super-tabs outer 2nd super-tab slides on clicking inner super-tab 2nd tab

### ISSUE THREAD

**Issue by pragatisamant** [zyra/ionic-super-tabs#443]
I am adding inner <super-tabs>(3,4) to <super-tabs-container> of outer <super-tabs>(1,2). The lib is not able to distinguish between the 2 supertabs. Clicking tab4 , outer super tab swipes to tab(2).
I have attached sample code
https://github.com/pragatisamant/git-issues/blob/master/nested-tabs.txt
[nested-tabs.txt](https://github.com/zyra/ionic-super-tabs/files/4831089/nested-tabs.txt)
In .ts file i use tabs = [3,4]

**Comment by ihadeed** [comment]
Nested swipeable super tabs will never be supported by this module. It's not a user friendly UX and not worth putting time into supporting it.
