### ISSUE TITLE
how to change the super tab color and moving speed 

### ISSUE THREAD

**Issue by bala-arun-s** [zyra/ionic-super-tabs#444]
I search a lot for how to change the super tab color and try to change the moving speed between tab to tab
I don't get a working solution .if you have any material to that please show me.And also color for selected tab too.please help me

**Comment by ihadeed** [comment]
Pass config to the super tabs component and configure the speed there

https://zyra.github.io/ionic-super-tabs/configuration/

https://zyra.github.io/ionic-super-tabs/components/super-tabs/


To change colors you can use a predefined ionic color that you have setup in variables, or pass a custom color using CSS variables

https://zyra.github.io/ionic-super-tabs/components/super-tabs-toolbar/

The example project shows all of the above
