### ISSUE TITLE
Angular 10 || 11 and Ionic 5: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s) error

### ISSUE THREAD

**Issue by almothafar** [zyra/ionic-super-tabs#460]
**Describe the bug**
While building production app for ionic 5 with Angular 10 or 11 I get an error with `Generic type 'ModuleWithProviders<T>' requires 1 type argument(s)` error

**To Reproduce**
Just upgrade your app to Angular 10 or above (which is used in Ionic 5).

**Screenshots**

![image](https://user-images.githubusercontent.com/13887564/105836614-1b43cb80-5fd6-11eb-9884-8b69082082e8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-bit & Ubuntu 20.4
 - Browser does not matter as it is build process
 - Version ^7.0.8

**Additional context**
The component working fine in Ionic 5 actually with latest angular (version 11), and I can workaround this issue by adding the following code to `app.module.ts`:

```typescript
declare module '@angular/core' {
	interface ModuleWithProviders<T = any> {
		ngModule: Type<T>;
		providers?: Provider[];
	}
}
```

**Comment by Juneezee** [comment]
I have created a pull request #463 that corrects this error.
