### ISSUE TITLE
tab underline is in wrong position in landscape view

### ISSUE THREAD

**Issue by tezcane** [zyra/ionic-super-tabs#53]
In v2.5.2 (and all previous versions) when you go from portrait to landscape mode, the underline under the right tab is in the wrong position. See attached screenshot, the blue underline needs to be directly under the right tab but it is offset towards the left.
![capture](https://cloud.githubusercontent.com/assets/17792056/26233126/1bf9c612-3c10-11e7-901a-bffb08e71ea3.PNG)

(P.S. accidentally posted this in example app)

**Comment by ihadeed** [comment]
Fixed in `ionic2-super-tabs@2.6.0`.

**Comment by tezcane** [comment]
Still broken in v2.6.1.  If you are in portrait mode, then switch to landscape same behavior in screenshot is still seen.

It works if you are always in landscape mode now though (launch app in landscape mode), I believe that was broken before and is now working.

**Comment by ihadeed** [comment]
Possibly related to #69
