### ISSUE TITLE
Page preloads other tab pages

### ISSUE THREAD

**Issue by kodeine** [zyra/ionic-super-tabs#61]
So i have a tabs page and it seems like it runs the next tabs code in advance. So the service is called on my 2nd tab when main tabs page is opened. Similarly, i move to 2nd tab then the 3rd tab page is preloaded making its service call. i tried changing the service call from `ngOnInit` to `ionViewWillEnter` without any luck.

Any idea's?

**Comment by karlvd** [comment]
This is related to #42 

It´s marked as closed, though we just communicated about this yesterday so I think it´s on the roadmap to be fixed

**Comment by kodeine** [comment]
Any idea when this will be resolved?

**Comment by karlvd** [comment]
+1 to get this solved.

I tested with the latest realease and `ionViewWillEnter / ionViewDidEnter` still fires on lazy loaded neighboring tabs.

Thanks for all your effort @ihadeed, apart form this Supertabs works great now. I tried to dig into the code but have a hard time figuring out what happens during load, seems like these events are fired implicitly by Ionic when the page loads and not triggered by supertabs, so I guess it will be hard to eliminate the "neighbor fires".

**Comment by robobobo** [comment]
I'm not sure if this is anything to do with Supertabs or not. Looks like there used to be an option to prevent preloading of `<ion-tabs>` but it was removed due to the way a new the tabs are preloaded

https://github.com/ionic-team/ionic/issues/8049#issuecomment-246355206
