### ISSUE TITLE
SearchBar doesn’t work correctly 

### ISSUE THREAD

**Issue by pradaries** [zyra/ionic-super-tabs#63]
Hi 😃 !!!

I have a very big problems with the plugin SuperTabs.

I have a searchBar and when I swipe to an another page my search is dead.
To explain my problems correctly look the picture.
Excuse me for my english, it isn't very good

![bug_searchbar_supertabs](https://cloud.githubusercontent.com/assets/17021987/26633801/eaaa2868-4614-11e7-8c25-b287fad021c3.gif)

Thank's in advance !! 😃 

My configuration :
Cordova CLI: 7.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
OS: Windows 10
Node Version: v6.10.3

**Comment by pradaries** [comment]
Hi ! 
So I think the view is not refresh. Can you help me for refresh a view on the slide because I have test refresher it doesn't work and I test window.location.reload or location.reload it doesn't work too.

Thannk you in advance.

**Comment by mumairofficial** [comment]
You should use page life hooks. to control this kind of behavior such as `ionViewDidEnter` `ionViewDidLeave` etc. Hopefully you get the point!

**Comment by pradaries** [comment]
Thank you @mumairofficial for your reply.
But where do you put the ionViewDidEnter ionViewDidLeave or other  option ?
Because I test this option but it doesn't work correctly or my code is not correct.
I will try this solution again.

Thank you in advance.

**Comment by ihadeed** [comment]
`ionViewDidEnter` and `ionViewDidLeave` are methods that you have to define in a component.

**Comment by pradaries** [comment]
Ok @ihadeed and thank you for clarifying this black point ;).
But after some test, I think this is not the solution. Because when I try to enter a new search (after the bug) the data is here (I see the new data in the inspector). 
My problem is just the ion-item result is not update with this new values. 
To resume my problems, my typescipt works correctly 😃 after I slide page but my html part (exactly the ion-item) not work correctly because it does not retrieve this new data.

I hope to put well expressed on the problem
