### ISSUE TITLE
lazy load images dont work on next tabs

### ISSUE THREAD

**Issue by kodeine** [zyra/ionic-super-tabs#64]
i am using [lazy load image](https://github.com/tjoskar/ng-lazyload-image) and second tab displays the images, when i swipe to the next tab it does not display the images until i slightly scroll the content. Its working fine without the super tabs. I guess its related to the issue that data on next tabs is already loaded in view while on the first tab mentioned in #61

**Comment by kodeine** [comment]
is there a way to get the `<ion-content #superTabsContaniner>` from a tabbed page so i can try lazy load image based on its scroll rather than current page.

**Comment by ihadeed** [comment]
@kodeine 

Try this:
```
<ion-content #mainContainer>
<super-tabs ...>
  <super-tab ... [navParams]="{ container: mainContainer }"></super-tab>
  ...
</super-tabs>
</ion-content>
```

**Comment by kodeine** [comment]
```html
<ion-content #mainContainer>
    <super-tabs id="mainTabs"
                tabsPlacement="top"
                [selectedTabIndex]="mySelectedIndex"
                [toolbarBackground]="toolbarBackground"
                [toolbarColor]="toolbarColor"
                indicatorColor="light"
                badgeColor="light"
                [config]="{ sideMenu: 'left' }"
                (tabSelect)="onTabSelect($event)">
        <super-tab [root]="tab0Root" icon="home" id="homeTab" [navParams]="{ container: mainContainer }"></super-tab>
        <super-tab [root]="tab1Root" icon="pulse" id="feedTab" [navParams]="{ container: mainContainer }"></super-tab>
        <super-tab [root]="tab2Root" icon="people" id="teamsTab" [navParams]="{ container: mainContainer }"></super-tab>
        <super-tab [root]="tab3Root" icon="book" id="historyTab" [navParams]="{ container: mainContainer }"></super-tab>
        <super-tab [root]="tab4Root" icon="map" id="nearbyTab" [navParams]="{ container: mainContainer }"></super-tab>
    </super-tabs>
</ion-content>
```

i get the following error,

```
Can't bind to 'navParams' since it isn't a known property of 'super-tab'.
1. If 'super-tab' is an Angular component and it has 'navParams' input, then verify that it is part of this module.
2. If 'super-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

**Comment by ihadeed** [comment]
Sorry it's `rootParams` not `navParams`

**Comment by kodeine** [comment]
rootParams worked but same issue with lazy loading image until i slightly scroll images wont be displayed

**Comment by ihadeed** [comment]
I'll look into this when I get a chance, but it's not a priority since it's not a bug/major bug with this module.

I recommend that for now you should refrain from using this library or the lazy loading library. Also, check out my [Ionic Image Loader](https://github.com/zyra/ionic-image-loader) module. It loads images in a native background thread, and it has a queue system to download images (first in, first out).. so it might be useful to you.

**Comment by kodeine** [comment]
sure i'll wait for this fix :+1:

**Comment by kodeine** [comment]
Any updates on this?
