### ISSUE TITLE
Issue with Super tabs and item-sliding

### ISSUE THREAD

**Issue by ManjuSagar** [zyra/ionic-super-tabs#65]
I'm using Super Tabs that works fine. i have 3 tabs in that Middle Tab has  some item listing at the bottom of the screen. i want to swipe the tabs when i swipe on screen top area. swiping should be disabled on all item listings.

**Comment by kodeine** [comment]
Same issue with me.

**Comment by aPinix** [comment]
Go see my solution on the issue [#139](https://github.com/zyra/ionic2-super-tabs/issues/139). Maybe it can help.
