### ISSUE TITLE
Providing a way to set heightOffset

### ISSUE THREAD

**Issue by darron1217** [zyra/ionic-super-tabs#67]
I got this white space between footer and super-tabs-container.

![image](https://cloud.githubusercontent.com/assets/8064923/26772473/a52485fa-4a00-11e7-926f-a5d729f660f5.png)

This problem caused by the fixed pixel of heightOffset variable
https://github.com/zyra/ionic2-super-tabs/blob/master/src/components/super-tabs.ts#L561

So.. @ihadeed Can you provide a way to set heightOffset as a initial config? :)

**Comment by ihadeed** [comment]
Sure I can add a config option
