### ISSUE TITLE
Tab toolbar indicator is not update width after add super-tab

### ISSUE THREAD

**Issue by icharge** [zyra/ionic-super-tabs#69]
Before add tab
![image](https://cloud.githubusercontent.com/assets/1619007/26777326/f96689e6-4a06-11e7-8e50-1bd6e6e69f0c.png)

After add tab by Array push
![image](https://cloud.githubusercontent.com/assets/1619007/26777408/47caf310-4a07-11e7-8d38-552a72e2ebfe.png)

my template 
```
<super-tabs #tabs [config]="superTabConfig" class="small">
    <super-tab title="{{ shopType }}" [root]="dummyCmp" *ngFor="let shopType of shopTypeList"></super-tab>
  </super-tabs>
```

**Comment by ihadeed** [comment]
Are you using the latest version of this module?

**Comment by icharge** [comment]
Yes. I using latest version

**Comment by MiLL10N** [comment]
+1

**Comment by MiLL10N** [comment]
+1

**Comment by giscafer** [comment]
+1,latest version。title="{{aaaa}}"

the indicator  style width `169px`  is not correct
    transform: translate3d(169px, 0px, 0px) scale3d(0.76, 1, 1);

**Comment by giscafer** [comment]
![20170708162732](https://user-images.githubusercontent.com/8676711/27983899-e636316a-63fa-11e7-86d0-e3b18ee995fb.png)

**Comment by SubinY** [comment]
same issue

**Comment by wjljack** [comment]
same issue

**Comment by nimtronican** [comment]
@ihadeed 
I too have the same issue with the tab. 
This issue occurs particularly in iOS 10.3.1 only. 
Other iOS and Android version working fine.
Any idea to solve this issue?
![tab-error-width-issue](https://user-images.githubusercontent.com/920411/31389104-aa1926d2-aded-11e7-8827-88ca37216c20.png)

**Comment by giscafer** [comment]
@nimtronican try this #121

**Comment by nimtronican** [comment]
@giscafer :  Thank you for the solution. It worked!
