### ISSUE TITLE
When I click tab, I want to locate it directly.

### ISSUE THREAD

**Issue by longdw** [zyra/ionic-super-tabs#70]
Assume that the current position is "0", when I click the "3" position tab, the tab will go through the position "1" and "2", my original intention is to direct positioning to "3".

**Comment by ihadeed** [comment]
This is currently possible by setting the `transitionDuration` to `0`. However, this would affect the transition speed of all animations.

See https://github.com/zyra/ionic2-super-tabs#config

Are you asking for another option to set the transition duration only when the user clicks on the tab buttons?

**Comment by longdw** [comment]
@ihadeed  yes, I mean that only when user clicks on the tab buttons and don't affect other animations.
