### ISSUE TITLE
Active tab change icon and text color

### ISSUE THREAD

**Issue by jeybs** [zyra/ionic-super-tabs#88]
Hi, is there a way to change the active tab icon and text color? thanks
tried using there css code but no luck. 

` .tabs-ios {
        a[aria-selected=false] {
            .tab-button-icon[ng-reflect-name=search], .tab-button-icon[aria-label="search outline"] {
                background-image: url(../assets/icon/tabNew1.png);
            }
        a[aria-selected=true] {
                  .tab-button-icon[ng-reflect-name=search], .tab-button-icon[aria-label=search] {
                background-image: url(../assets/icon/tabNew1-active.png);
            }
    }`

**Comment by philipgriffin** [comment]
https://github.com/zyra/ionic2-super-tabs/blob/master/README.md#colors

See the example, if that's what you're looking for

**Comment by ihadeed** [comment]
Are you asking how to set a custom colour for active tabs (that is different than the rest)? or how to customize the colours globally?

**Comment by jeybs** [comment]
@ihadeed yes i'm asking how to set custom color for the text for  active tab(that is different than the rest).. not globablly

**Comment by ihadeed** [comment]
That would be a new feature that we need to add.

**Comment by andrews3** [comment]
I don't know if you still have this problem, but if anyone else needs it
```
.selected {
    color: map_get($colors, primary) !important;
  }

  super-tab-button {
    color: white;
  }
```
When the tab is selected, a css class called `.selected` is added to the tab button, só just add the code above in your css file, but is important not set the toolbarColor property in the Super Tabs component
